"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {ApprovedContractClause,ContractGroup,deleteApprovedContractClause,listApprovedContractClauses,listContractCatalog,saveApprovedContractClause} from "../../../lib/api";
const pageSize=20;
export default function ContractClausesPage(){
 const [items,setItems]=useState<ApprovedContractClause[]>([]),[groups,setGroups]=useState<ContractGroup[]>([]),[page,setPage]=useState(1),[totalPages,setTotalPages]=useState(1),[error,setError]=useState(""),[editing,setEditing]=useState<ApprovedContractClause>();
 const [contractGroupId,setGroupId]=useState(""),[code,setCode]=useState(""),[title,setTitle]=useState(""),[text,setText]=useState(""),[order,setOrder]=useState(1),[isRequired,setRequired]=useState(false),[isActive,setActive]=useState(true);
 const load=useCallback(async(p=page)=>{try{const r=await listApprovedContractClauses(undefined,p,pageSize);setItems(r.items);setPage(r.pageNumber);setTotalPages(Math.max(1,r.totalPages));}catch{setError("دریافت بندهای قرارداد انجام نشد.");}},[page]);
 useEffect(()=>{void load(1);listContractCatalog<ContractGroup>("groups",1,100).then(x=>setGroups(x.items.filter(g=>g.isActive))).catch(()=>setError("دریافت گروه‌ها انجام نشد."));},[]);
 function reset(){setEditing(undefined);setGroupId("");setCode("");setTitle("");setText("");setOrder(1);setRequired(false);setActive(true);}
 async function submit(e:FormEvent){e.preventDefault();try{await saveApprovedContractClause({contractGroupId,code,title,text,order,isRequired,isActive},editing?.id);reset();await load(editing?page:1);}catch(e){setError(e instanceof Error?e.message:"خطا در ذخیره");}}
 function edit(x:ApprovedContractClause){setEditing(x);setGroupId(x.contractGroupId);setCode(x.code);setTitle(x.title);setText(x.text);setOrder(x.order);setRequired(x.isRequired);setActive(x.isActive);}
 async function toggle(x:ApprovedContractClause){await saveApprovedContractClause({contractGroupId:x.contractGroupId,code:x.code,title:x.title,text:x.text,order:x.order,isRequired:x.isRequired,isActive:!x.isActive},x.id);await load();}
 async function remove(id:string){if(window.confirm("این بند به‌صورت نرم حذف شود؟")){await deleteApprovedContractClause(id);await load(items.length===1&&page>1?page-1:page);}}
 return <main className="app-shell" dir="rtl"><section className="page-content"><header className="page-header"><div><p className="eyebrow">اطلاعات پایه</p><h1>بندهای تأییدشده قرارداد</h1><p>بندهای معتبر هر گروه برای تولید قراردادهای جدید استفاده و همراه پیش‌نویس snapshot می‌شوند.</p></div></header>
 <article className="panel"><h2>{editing?"ویرایش بند":"ثبت بند تأییدشده"}</h2><form className="form-grid" onSubmit={submit}><label className="field"><span>گروه قرارداد *</span><select required value={contractGroupId} onChange={e=>setGroupId(e.target.value)}><option value="">انتخاب کنید</option>{groups.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field"><span>کد *</span><input required value={code} onChange={e=>setCode(e.target.value)}/></label><label className="field"><span>عنوان *</span><input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field"><span>ترتیب</span><input type="number" min={0} value={order} onChange={e=>setOrder(Number(e.target.value))}/></label><label className="field full"><span>متن بند *</span><textarea required value={text} onChange={e=>setText(e.target.value)}/></label><label className="field"><span><input type="checkbox" checked={isRequired} onChange={e=>setRequired(e.target.checked)}/> بند الزامی</span></label><label className="field"><span><input type="checkbox" checked={isActive} onChange={e=>setActive(e.target.checked)}/> فعال</span></label><div><button className="primary-button">{editing?"ذخیره تغییرات":"ثبت بند"}</button>{editing&&<button type="button" className="ghost-button" onClick={reset}>انصراف</button>}</div></form></article>
 <article className="panel"><h2>فهرست بندها</h2>{error&&<p className="error-text">{error}</p>}{items.map(x=><div className="catalog-row" key={x.id}><span><strong>{x.code} — {x.title}</strong><small>{x.groupName} · {x.text}</small></span><b>{x.isRequired?"الزامی":"اختیاری"} / {x.isActive?"فعال":"غیرفعال"}</b><button onClick={()=>void toggle(x)}>{x.isActive?"غیرفعال‌سازی":"فعال‌سازی"}</button><button onClick={()=>edit(x)}>ویرایش</button><button onClick={()=>void remove(x.id)}>حذف</button></div>)}{!items.length&&<p>هنوز بندی ثبت نشده است.</p>}<nav className="pagination"><button disabled={page<=1} onClick={()=>void load(page-1)}>قبلی</button><span>صفحه {page} از {totalPages}</span><button disabled={page>=totalPages} onClick={()=>void load(page+1)}>بعدی</button></nav></article></section></main>;
}
