"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createIdentityRole, deleteIdentityRole, IdentityRole, listIdentityRoles, restoreIdentityRole, updateIdentityRole } from "../../../lib/api";
import AccessShell from "../AccessShell";
export default function RolesPage(){
 const [items,setItems]=useState<IdentityRole[]>([]),[name,setName]=useState(""),[displayName,setDisplayName]=useState(""),[edit,setEdit]=useState<IdentityRole|null>(null),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[busy,setBusy]=useState(false);
 async function load(){setItems(await listIdentityRoles())}useEffect(()=>{void load().catch(()=>setMessage("دریافت نقش‌ها انجام نشد."))},[]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return q?items.filter(x=>`${x.name} ${x.displayName}`.toLowerCase().includes(q)):items},[items,search]);
 function reset(){setEdit(null);setName("");setDisplayName("")}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{if(edit)await updateIdentityRole(edit.id,{name,displayName});else await createIdentityRole({name,displayName});reset();await load();setMessage("نقش با موفقیت ذخیره شد.")}catch(error){setMessage(error instanceof Error?error.message:"ذخیره نقش انجام نشد.")}finally{setBusy(false)}}
 return <AccessShell title="نقش‌ها" description="مسئولیت‌های سازمانی را تعریف کنید و سپس مجوزهای هر نقش را مستقل تنظیم کنید." badge={`${items.filter(x=>!x.isDeleted).length} نقش`}>
  <section className="access-dashboard-grid roles-layout"><article className="access-panel access-list-panel"><div className="access-panel-head"><div><h2>نقش‌های سازمان</h2><p>نقش‌های سیستمی محافظت می‌شوند</p></div><button className="access-new" onClick={reset}>+ نقش جدید</button></div>
   <label className="access-search standalone"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی نقش..."/></label>
   <div className="role-card-grid">{visible.map(role=><article className={`role-card ${edit?.id===role.id?"selected":""}`} key={role.id}><div className="role-card-icon">{role.displayName.charAt(0)}</div><div className="role-card-body"><div><strong>{role.displayName}</strong><b className={`access-status ${role.isDeleted?"deleted":role.isSystem?"system":"active"}`}>{role.isDeleted?"حذف‌شده":role.isSystem?"سیستمی":"سفارشی"}</b></div><small>{role.name}</small><footer><Link href={`/access/role-permissions?role=${role.id}`}>تنظیم دسترسی‌ها</Link>{!role.isSystem&&(role.isDeleted?<button onClick={()=>void restoreIdentityRole(role.id).then(load)}>بازیابی</button>:<><button onClick={()=>{setEdit(role);setName(role.name);setDisplayName(role.displayName)}}>ویرایش</button><button className="danger" onClick={()=>window.confirm("این نقش حذف شود؟")&&void deleteIdentityRole(role.id).then(load)}>حذف</button></>)}</footer></div></article>)}</div>
  </article><article className="access-panel access-editor"><div className="access-panel-head"><div><h2>{edit?"ویرایش نقش":"تعریف نقش جدید"}</h2><p>عنوان قابل نمایش و شناسهٔ سیستمی را وارد کنید</p></div>{edit&&<button className="access-icon-button" onClick={reset}>×</button>}</div><form onSubmit={e=>void submit(e)}><div className="access-form-grid"><label className="full"><span>عنوان فارسی نقش</span><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="مثلاً مدیر امور قراردادها" required/></label><label className="full"><span>نام سیستمی</span><input dir="ltr" value={name} onChange={e=>setName(e.target.value)} placeholder="ContractManager" required/></label></div><div className="access-info-box">پس از ایجاد نقش، از صفحه «دسترسی نقش‌ها» مجوزهای آن را انتخاب کنید.</div>{message&&<p className="access-message">{message}</p>}<footer><button type="button" onClick={reset}>انصراف</button><button className="primary" disabled={busy}>{busy?"در حال ذخیره...":edit?"ذخیره نقش":"ایجاد نقش"}</button></footer></form></article></section>
 </AccessShell>;
}
