// <auto-generated />
using System;
using Healan.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Healan.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208163749_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppointmentServiceType", b =>
                {
                    b.Property<long>("AppointmentsAppointmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTypesServiceTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("AppointmentsAppointmentId", "ServiceTypesServiceTypeId");

                    b.HasIndex("ServiceTypesServiceTypeId");

                    b.ToTable("AppointmentServiceType");
                });

            modelBuilder.Entity("Healan.Domain.Appointments.Entities.Appointment", b =>
                {
                    b.Property<long>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<byte>("AppointmentTypeId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("ConfirmPrimaryInsuranceCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ConfirmSecondInsuranceCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PrimaryInsuranceCompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SecondInsuranceCompanyId")
                        .HasColumnType("bigint");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrimaryInsuranceCompanyId");

                    b.HasIndex("SecondInsuranceCompanyId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Attachments.Entities.Attachment", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignerFirstName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SignerLastName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SignerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("FileId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Companies.Entities.Company", b =>
                {
                    b.Property<long>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CompanyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CategoryNumber")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CompanyRegistrationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EstablishmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Landline")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LatinCompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ParentCompanyRef")
                        .HasColumnType("bigint");

                    b.Property<string>("PrefixNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CompanyId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("CompanyRegistrationTypeId");

                    b.HasIndex("ParentCompanyRef");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Companies.Entities.CompanyRegistrationType", b =>
                {
                    b.Property<int>("CompanyRegistrationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyRegistrationTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CompanyRegistrationTypeId");

                    b.ToTable("CompanyRegistrationTypes", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Doctors.Entities.Doctor", b =>
                {
                    b.Property<long>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DoctorId"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MedicalGroupTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalSystemNumber")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonnelNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("DoctorId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Insurances.Entities.InsuranceCompany", b =>
                {
                    b.Property<long>("InsuranceCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InsuranceCompanyId"));

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<int>("InsuranceTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsuranceCompanyId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("InsuranceCompanies", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Insurances.Entities.InsuranceContract", b =>
                {
                    b.Property<long>("InsuranceContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InsuranceContractId"));

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("InsuranceCompanyId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InsuranceContractId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("InsuranceCompanyId");

                    b.ToTable("InsuranceContracts", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Insurances.Entities.InsuranceContractService", b =>
                {
                    b.Property<long>("InsuranceContractServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InsuranceContractServiceId"));

                    b.Property<decimal>("CoPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoveragePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("InsuranceContractId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ServiceTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("InsuranceContractServiceId");

                    b.HasIndex("InsuranceContractId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("InsuranceContractServices", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Insurances.Entities.InsuranceType", b =>
                {
                    b.Property<int>("InsuranceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("InsuranceTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InsuranceTypeId");

                    b.ToTable("InsuranceTypes", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Invoices.Entities.Invoice", b =>
                {
                    b.Property<long>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceId"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasComment("کد نوبت");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<byte>("InvoiceStatusTypeId")
                        .HasColumnType("tinyint")
                        .HasComment("وضعیت صورت حساب");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PatientPayable")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[TotalAmount]-([PrimaryInsuranceCovered]+[SecondaryInsuranceCovered])", true)
                        .HasComment("سهم بیمار");

                    b.Property<decimal>("PrimaryInsuranceCovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("پوشش بیمه اصلی");

                    b.Property<decimal>("SecondaryInsuranceCovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("پوشش بیمه تمکیلی");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("مبلغ کل");

                    b.HasKey("InvoiceId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Invoices.Entities.InvoiceItem", b =>
                {
                    b.Property<long>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceItemId"));

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Quantity]*[UnitPrice]", true)
                        .HasComment("مبلغ کل");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<long?>("InsuranceContractServiceId")
                        .HasColumnType("bigint")
                        .HasComment("تعرفه  با بیمه تکمیلی در صورت  دارا بودن بیمه تکمیلی بیمه در قرارداد بیمار");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasComment("کد فاکتور");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PatientPayable")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("([Quantity]*[UnitPrice])-([PrimaryInsuranceCovered]+[SecondaryInsuranceCovered])", true)
                        .HasComment("سهم بیمار");

                    b.Property<decimal>("PrimaryInsuranceCovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("پوشش بیمه اصلی");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("تعداد");

                    b.Property<decimal>("SecondaryInsuranceCovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("پوشش بیمه تمکیلی");

                    b.Property<long>("ServiceTypeId")
                        .HasColumnType("bigint")
                        .HasComment("نوع خدمت");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("قیمت واحد");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("InsuranceContractServiceId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("InvoiceItems", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Invoices.Entities.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PatientShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("PaymentMethodTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaymentStatusTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("PrimaryInsuranceContractId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrimaryInsuranceConvered")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("PrimaryInsuranceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SecondaryInsuranceContractId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SecondaryInsuranceCovered")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SecondaryInsuranceId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.MedicalFeeServices.Entities.CategoryType", b =>
                {
                    b.Property<byte>("CategoryTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("CategoryTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryTypeId");

                    b.ToTable("CategoryTypes", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.MedicalFeeServices.Entities.MedicalFeeService", b =>
                {
                    b.Property<long>("MedicalFeeServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MedicalFeeServiceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("تا تاریخ");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("فعال/غیرفعال");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasComment("مبلغ تعرفه");

                    b.Property<long>("ServiceTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("از تاریخ");

                    b.HasKey("MedicalFeeServiceId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("MedicalFeeServices", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Menus.Entities.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<byte>("HealanTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("MenuTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MenuWeight")
                        .HasColumnType("int");

                    b.HasKey("MenuId");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Menus.Entities.Submenu", b =>
                {
                    b.Property<int>("SubmenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmenuId"));

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("ConfirmApiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("FindApiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(350)");

                    b.Property<bool>("HasSignature")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListApiName")
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("MenuId")
                        .HasColumnType("Int");

                    b.Property<string>("RejectApiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("SaveApiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("SignatureSaveApiName")
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("SubmenuRow")
                        .HasColumnType("int");

                    b.Property<string>("SubmenuTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SubmenuWeight")
                        .HasColumnType("int");

                    b.HasKey("SubmenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("Submenu", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.ImagingRequest", b =>
                {
                    b.Property<long>("ImagingRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImagingRequestId"));

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<int>("ImageTypeId")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("PrescriptionId")
                        .HasColumnType("bigint");

                    b.HasKey("ImagingRequestId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("ImagingRequests", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.ImagingResult", b =>
                {
                    b.Property<long>("ImagingResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImagingResultId"));

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<long>("ImagingRequestId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ImagingResultId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ImagingRequestId");

                    b.ToTable("ImagingResults", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.LabTestRequest", b =>
                {
                    b.Property<long>("LabTestRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LabTestRequestId"));

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabTestType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("PrescriptionId")
                        .HasColumnType("bigint");

                    b.HasKey("LabTestRequestId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("LabTestRequests", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.LabTestResult", b =>
                {
                    b.Property<long>("LabTestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LabTestResultId"));

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabResultData")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("LabTestRequestId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LabTestResultId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("LabTestRequestId");

                    b.ToTable("LabTestResults", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.Prescription", b =>
                {
                    b.Property<long>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PrescriptionId"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NextAppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.PrescriptionDrug", b =>
                {
                    b.Property<long>("PrescriptionDrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PrescriptionDrugId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PrescriptionId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsageInstructions")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("PrescriptionDrugId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionDrugs", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Patients.Entities.Patient", b =>
                {
                    b.Property<long>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PatientId"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.PublicInfos.Entities.ServiceType", b =>
                {
                    b.Property<long>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ServiceTypeId"));

                    b.Property<byte>("CategoryTypeId")
                        .HasColumnType("tinyint")
                        .HasComment("دسته بندی");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("کد");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("توضیحات");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("عنوان");

                    b.HasKey("ServiceTypeId");

                    b.ToTable("ServiceTypes", (string)null);
                });

            modelBuilder.Entity("Healan.Domain.Users.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<string>("ExtensionCompanyPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("IdentityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Landline")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonnelNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PrefixNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserTypes", (string)null);
                });

            modelBuilder.Entity("AppointmentServiceType", b =>
                {
                    b.HasOne("Healan.Domain.Appointments.Entities.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentsAppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Healan.Domain.PublicInfos.Entities.ServiceType", null)
                        .WithMany()
                        .HasForeignKey("ServiceTypesServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Healan.Domain.Appointments.Entities.Appointment", b =>
                {
                    b.HasOne("Healan.Domain.Doctors.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Healan.Domain.Patients.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Healan.Domain.Insurances.Entities.InsuranceCompany", "PrimaryInsuranceCompany")
                        .WithMany("PrimaryInsuranceAppointments")
                        .HasForeignKey("PrimaryInsuranceCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Healan.Domain.Insurances.Entities.InsuranceCompany", "SecondInsuranceCompany")
                        .WithMany("SecondInsuranceAppointments")
                        .HasForeignKey("SecondInsuranceCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("PrimaryInsuranceCompany");

                    b.Navigation("SecondInsuranceCompany");
                });

            modelBuilder.Entity("Healan.Domain.Companies.Entities.Company", b =>
                {
                    b.HasOne("Healan.Domain.Attachments.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Healan.Domain.Companies.Entities.CompanyRegistrationType", "CompanyRegistrationType")
                        .WithMany("Companies")
                        .HasForeignKey("CompanyRegistrationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Healan.Domain.Companies.Entities.Company", "ParentCompany")
                        .WithMany("ChildCompanies")
                        .HasForeignKey("ParentCompanyRef")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Attachment");

                    b.Navigation("CompanyRegistrationType");

                    b.Navigation("ParentCompany");
                });

            modelBuilder.Entity("Healan.Domain.Doctors.Entities.Doctor", b =>
                {
                    b.HasOne("Healan.Domain.Companies.Entities.Company", "Company")
                        .WithMany("Doctors")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Healan.Domain.Users.Entities.User", "User")
                        .WithMany("Doctors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Healan.Domain.Insurances.Entities.InsuranceCompany", b =>
                {
                    b.HasOne("Healan.Domain.Attachments.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("Healan.Domain.Insurances.Entities.InsuranceContract", b =>
                {
                    b.HasOne("Healan.Domain.Attachments.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("Healan.Domain.Insurances.Entities.InsuranceCompany", "InsuranceCompany")
                        .WithMany("InsuranceContracts")
                        .HasForeignKey("InsuranceCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("InsuranceCompany");
                });

            modelBuilder.Entity("Healan.Domain.Insurances.Entities.InsuranceContractService", b =>
                {
                    b.HasOne("Healan.Domain.Insurances.Entities.InsuranceContract", "InsuranceContract")
                        .WithMany("InsuranceContractServices")
                        .HasForeignKey("InsuranceContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Healan.Domain.PublicInfos.Entities.ServiceType", "ServiceType")
                        .WithMany("InsuranceContractServices")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InsuranceContract");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Healan.Domain.Invoices.Entities.Invoice", b =>
                {
                    b.HasOne("Healan.Domain.Appointments.Entities.Appointment", "Appointment")
                        .WithMany("Invoices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Healan.Domain.Invoices.Entities.InvoiceItem", b =>
                {
                    b.HasOne("Healan.Domain.Insurances.Entities.InsuranceContractService", "InsuranceContractService")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InsuranceContractServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Healan.Domain.Invoices.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Healan.Domain.PublicInfos.Entities.ServiceType", "ServiceType")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InsuranceContractService");

                    b.Navigation("Invoice");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Healan.Domain.Invoices.Entities.Payment", b =>
                {
                    b.HasOne("Healan.Domain.Invoices.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Healan.Domain.MedicalFeeServices.Entities.MedicalFeeService", b =>
                {
                    b.HasOne("Healan.Domain.PublicInfos.Entities.ServiceType", "ServiceType")
                        .WithMany("MedicalFeeServices")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Healan.Domain.Menus.Entities.Submenu", b =>
                {
                    b.HasOne("Healan.Domain.Menus.Entities.Menu", "Menu")
                        .WithMany("Submenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.ImagingRequest", b =>
                {
                    b.HasOne("Healan.Domain.Attachments.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("Healan.Domain.Orders.Entities.Prescription", "Prescription")
                        .WithMany("ImagingRequests")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.ImagingResult", b =>
                {
                    b.HasOne("Healan.Domain.Attachments.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("Healan.Domain.Orders.Entities.ImagingRequest", "ImagingRequest")
                        .WithMany("ImagingResults")
                        .HasForeignKey("ImagingRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("ImagingRequest");
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.LabTestRequest", b =>
                {
                    b.HasOne("Healan.Domain.Attachments.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("Healan.Domain.Orders.Entities.Prescription", "Prescription")
                        .WithMany("LabTestRequests")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.LabTestResult", b =>
                {
                    b.HasOne("Healan.Domain.Attachments.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("Healan.Domain.Orders.Entities.LabTestRequest", "LabTestRequest")
                        .WithMany("LabTestResults")
                        .HasForeignKey("LabTestRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("LabTestRequest");
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.Prescription", b =>
                {
                    b.HasOne("Healan.Domain.Appointments.Entities.Appointment", "Appointment")
                        .WithMany("Prescriptions")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.PrescriptionDrug", b =>
                {
                    b.HasOne("Healan.Domain.Orders.Entities.Prescription", "Prescription")
                        .WithMany("PrescriptionDrugs")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Healan.Domain.Patients.Entities.Patient", b =>
                {
                    b.HasOne("Healan.Domain.Users.Entities.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Healan.Domain.Users.Entities.User", b =>
                {
                    b.HasOne("Healan.Domain.Attachments.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("Healan.Domain.Companies.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Attachment");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Healan.Domain.Appointments.Entities.Appointment", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Healan.Domain.Companies.Entities.Company", b =>
                {
                    b.Navigation("ChildCompanies");

                    b.Navigation("Doctors");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Healan.Domain.Companies.Entities.CompanyRegistrationType", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Healan.Domain.Doctors.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Healan.Domain.Insurances.Entities.InsuranceCompany", b =>
                {
                    b.Navigation("InsuranceContracts");

                    b.Navigation("PrimaryInsuranceAppointments");

                    b.Navigation("SecondInsuranceAppointments");
                });

            modelBuilder.Entity("Healan.Domain.Insurances.Entities.InsuranceContract", b =>
                {
                    b.Navigation("InsuranceContractServices");
                });

            modelBuilder.Entity("Healan.Domain.Insurances.Entities.InsuranceContractService", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("Healan.Domain.Invoices.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Healan.Domain.Menus.Entities.Menu", b =>
                {
                    b.Navigation("Submenus");
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.ImagingRequest", b =>
                {
                    b.Navigation("ImagingResults");
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.LabTestRequest", b =>
                {
                    b.Navigation("LabTestResults");
                });

            modelBuilder.Entity("Healan.Domain.Orders.Entities.Prescription", b =>
                {
                    b.Navigation("ImagingRequests");

                    b.Navigation("LabTestRequests");

                    b.Navigation("PrescriptionDrugs");
                });

            modelBuilder.Entity("Healan.Domain.Patients.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Healan.Domain.PublicInfos.Entities.ServiceType", b =>
                {
                    b.Navigation("InsuranceContractServices");

                    b.Navigation("InvoiceItems");

                    b.Navigation("MedicalFeeServices");
                });

            modelBuilder.Entity("Healan.Domain.Users.Entities.User", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
