// <auto-generated />
using System;
using FileManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileManager.Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime");

                    b.Property<long>("DownloadedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BigInt")
                        .HasDefaultValue(0L);

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("FileSize")
                        .HasColumnType("float");

                    b.Property<short>("FileTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<string>("JsonInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RequestIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SavedFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeId");

                    b.ToTable("File", (string)null);
                });

            modelBuilder.Entity("FileManager.Domain.Entities.FileType", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("FileType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Image"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Video"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Document"
                        },
                        new
                        {
                            Id = (short)4,
                            Name = "Excel"
                        },
                        new
                        {
                            Id = (short)5,
                            Name = "PDF"
                        });
                });

            modelBuilder.Entity("FileManager.Domain.Entities.PdfSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Certificate")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("CertificationLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("Digest")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("HashAlgorithm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImageDataUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<float?>("LowerLeftX")
                        .HasColumnType("real");

                    b.Property<float?>("LowerLeftY")
                        .HasColumnType("real");

                    b.Property<int?>("Page")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("ParentPdfSignatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SignatureAttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("UpperRightX")
                        .HasColumnType("real");

                    b.Property<float?>("UpperRightY")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ParentPdfSignatureId");

                    b.ToTable("PdfSignature", (string)null);
                });

            modelBuilder.Entity("FileManager.Domain.Entities.File", b =>
                {
                    b.HasOne("FileManager.Domain.Entities.FileType", "FileType")
                        .WithMany("Files")
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_File_FileType");

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("FileManager.Domain.Entities.PdfSignature", b =>
                {
                    b.HasOne("FileManager.Domain.Entities.PdfSignature", "ParentPdfSignature")
                        .WithMany("ChildPdfSignatures")
                        .HasForeignKey("ParentPdfSignatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPdfSignature");
                });

            modelBuilder.Entity("FileManager.Domain.Entities.FileType", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("FileManager.Domain.Entities.PdfSignature", b =>
                {
                    b.Navigation("ChildPdfSignatures");
                });
#pragma warning restore 612, 618
        }
    }
}
