"use client";
import {FormEvent,useEffect,useState} from "react";
import {createIdentityUser,deleteIdentityUser,IdentityRole,IdentityUser,listIdentityRoles,listIdentityUsers,restoreIdentityUser,updateIdentityUser} from "../../../lib/api";
export default function UsersPage(){
 const [users,setUsers]=useState<IdentityUser[]>([]),[roles,setRoles]=useState<IdentityRole[]>([]),[edit,setEdit]=useState<IdentityUser|null>(null),[includeDeleted,setIncludeDeleted]=useState(false),[userName,setUserName]=useState(""),[password,setPassword]=useState(""),[firstName,setFirstName]=useState(""),[lastName,setLastName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[active,setActive]=useState(true),[roleIds,setRoleIds]=useState<string[]>([]),[message,setMessage]=useState("");
 async function load(deleted=includeDeleted){const [u,r]=await Promise.all([listIdentityUsers(deleted),listIdentityRoles()]);setUsers(u);setRoles(r.filter(x=>!x.isDeleted))}useEffect(()=>{void load()},[includeDeleted]);
 function reset(){setEdit(null);setUserName("");setPassword("");setFirstName("");setLastName("");setEmail("");setPhone("");setActive(true);setRoleIds([])}
 function select(u:IdentityUser){setEdit(u);setUserName(u.userName);setFirstName(u.firstName);setLastName(u.lastName);setEmail(u.email||"");setPhone(u.phoneNumber||"");setActive(u.isActive);setRoleIds(u.roleIds);setPassword("")}
 async function submit(e:FormEvent){e.preventDefault();try{const input={userName,firstName,lastName,email:email||undefined,phoneNumber:phone||undefined,password:password||undefined,isActive:active,roleIds};if(edit)await updateIdentityUser(edit.id,input);else await createIdentityUser({...input,password});reset();await load();setMessage("ذخیره شد.")}catch(error){setMessage(error instanceof Error?error.message:"ذخیره کاربر انجام نشد.")}}
 return <main className="access-page" dir="rtl"><header className="access-header"><div><span>مدیریت کاربران و دسترسی‌ها</span><h1>کاربران</h1><p>اطلاعات کاربر، وضعیت و نقش‌های او را مدیریت کنید.</p></div></header><section className="access-card"><form className="form-grid" onSubmit={e=>void submit(e)}><input placeholder="نام کاربری" value={userName} onChange={e=>setUserName(e.target.value)} required/><input placeholder={edit?"رمز جدید (اختیاری)":"رمز اولیه"} type="password" value={password} onChange={e=>setPassword(e.target.value)} required={!edit}/><input placeholder="نام" value={firstName} onChange={e=>setFirstName(e.target.value)} required/><input placeholder="نام خانوادگی" value={lastName} onChange={e=>setLastName(e.target.value)} required/><input placeholder="ایمیل" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="تلفن" value={phone} onChange={e=>setPhone(e.target.value)}/><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> فعال</label><div className="choice-grid">{roles.map(r=><label key={r.id}><input type="checkbox" checked={roleIds.includes(r.id)} onChange={e=>setRoleIds(e.target.checked?[...roleIds,r.id]:roleIds.filter(id=>id!==r.id))}/>{r.displayName}</label>)}</div><button className="primary-button">{edit?"ذخیره تغییرات":"ثبت کاربر"}</button>{edit&&<button type="button" onClick={reset}>انصراف</button>}</form><label><input type="checkbox" checked={includeDeleted} onChange={e=>setIncludeDeleted(e.target.checked)}/> نمایش حذف‌شده‌ها</label><p>{message}</p>{users.map(u=><div className="catalog-row" key={u.id}><span>{u.firstName} {u.lastName} — {u.userName}</span><b>{u.isDeleted?"حذف‌شده":u.isActive?"فعال":"غیرفعال"}</b>{u.isDeleted?<button onClick={()=>void restoreIdentityUser(u.id).then(()=>load())}>بازیابی</button>:<><button onClick={()=>select(u)}>ویرایش</button>{u.userName.toLowerCase()!=="adminuser"&&<button onClick={()=>window.confirm("کاربر حذف نرم شود؟")&&void deleteIdentityUser(u.id).then(()=>load())}>حذف</button>}</>}</div>)}</section></main>;
}
