"use client";
import { FormEvent, useEffect, useState } from "react";
import { ContractBaseDocument, deleteContractCatalog, DocumentListItem, listContractCatalog, listDocuments, saveContractCatalog } from "../../../lib/api";
const size=20;
export default function BaseDocumentsPage(){
 const [items,setItems]=useState<ContractBaseDocument[]>([]),[documents,setDocuments]=useState<DocumentListItem[]>([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[name,setName]=useState(""),[documentId,setDocumentId]=useState(""),[description,setDescription]=useState(""),[active,setActive]=useState(true),[edit,setEdit]=useState<ContractBaseDocument|null>(null),[message,setMessage]=useState("");
 async function load(p=page){try{const [r,d]=await Promise.all([listContractCatalog<ContractBaseDocument>("base-documents",p,size),listDocuments()]);setItems(r.items);setPage(r.pageNumber);setPages(Math.max(1,r.totalPages));setDocuments(d.items)}catch{setMessage("دریافت اسناد مبنا انجام نشد.")}}useEffect(()=>{void load(1)},[]);
 function reset(){setEdit(null);setName("");setDocumentId("");setDescription("");setActive(true)}
 async function submit(e:FormEvent){e.preventDefault();if(!name.trim()||!documentId)return;try{await saveContractCatalog("base-documents",{name,documentId,description:description||null,isActive:active},edit?.id);reset();await load(edit?page:1);setMessage("ذخیره شد.")}catch{setMessage("ذخیره سند مبنا انجام نشد.")}}
 return <main className="app-shell" dir="rtl"><section className="page-content"><header className="page-header"><p className="eyebrow">اطلاعات پایه</p><h1>اسناد مبنا</h1><p>سندهای قابل انتخاب به‌عنوان مبنای قرارداد را از مخزن اسناد سازمان تعیین کنید.</p></header><article className="panel"><form className="form-grid" onSubmit={e=>void submit(e)}><input placeholder="نام نمایشی" value={name} onChange={e=>setName(e.target.value)} required/><select value={documentId} onChange={e=>setDocumentId(e.target.value)} required><option value="">انتخاب سند</option>{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><input placeholder="توضیحات" value={description} onChange={e=>setDescription(e.target.value)}/><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> فعال</label><button className="primary-button">{edit?"ذخیره":"ثبت سند مبنا"}</button>{edit&&<button type="button" onClick={reset}>انصراف</button>}</form></article><article className="panel"><h2>فهرست اسناد مبنا</h2><p>{message}</p>{items.map(x=><div className="catalog-row" key={x.id}><span>{x.name} — {x.documentTitle}</span><b>{x.isActive?"فعال":"غیرفعال"}</b><button onClick={()=>void saveContractCatalog("base-documents",{name:x.name,documentId:x.documentId,description:x.description||null,isActive:!x.isActive},x.id).then(()=>load())}>{x.isActive?"غیرفعال‌سازی":"فعال‌سازی"}</button><button onClick={()=>{setEdit(x);setName(x.name);setDocumentId(x.documentId);setDescription(x.description||"");setActive(x.isActive)}}>ویرایش</button><button onClick={()=>window.confirm("حذف نرم شود؟")&&void deleteContractCatalog("base-documents",x.id).then(()=>load())}>حذف</button></div>)}<nav className="pagination"><button disabled={page===1} onClick={()=>void load(page-1)}>قبلی</button><span>{page} از {pages}</span><button disabled={page===pages} onClick={()=>void load(page+1)}>بعدی</button></nav></article></section></main>
}
