import { lazy, Outlet } from '@tse/utils';
import {
  Cartable,
  RequestStartMarketing,
  RejectionReason,
  InstrumentParameter,
  MarketingFund,
  Instrument,
  RequestDetails,
  Profile,
  CancelRequest,
  ProfileDetail,
  AccessRequestDetail,
  QuitReason,
  MarketParameter,
  ExtendingTime,
  RequestReport,
  InstrumentList,
  NewInstrument,
  InstrumentTradeOptionDetails,
  InstrumentOptionDetails,
  InstrumentFutureDetails,
  InstrumentDebitDetails,
  BlockTransaction,
  BlockTransactionPreview,
  BlockRequestTracking,
  BlockRequestDetails,
  BlockCartable,
  BlockChangeStatus,
  InstrumentFundDetails,
  RequestTransferStock,
  RequestDetailsTransferStock,
  SetDeadLineTransferStock,
  SendAttachmentTransferStock,
  InitialSupplyTransaction,
  InitialSupplyRequestDetails,
  WholesaleCashRequest,
  WholeSaleSellRequestTracking,
  WholeSaleSellRequestDetailsExpert,
  WholeSaleSellRequestDetails,
  RequestChangeParameter,
  RequestChangeParameterDetails,
  RequestChangeBroker,
  RequestChangeBrokerDetails,
  MessagesList,
  ParameterReports,
  InstrumentMarketMaker,
  ManageRole,
  ChangeParameterReport,
  UserManagement,
  CallbackPage,
  RequestBuyAdList,
  CancelRequestSellWholesaleList,
  CancelRequestBuyWholesaleList,
  CertaintySellWholesaleList,
  RequestBuyWholeSale,
  RequestDetailBuyWholeSale,
  RequestCancelBuyWholesale,
  RequestDetailCancelBuyWholesale,
  CancelRequestSellWholesale,
  CancelRequestDetailSellWholesale,
  CertaintySellWholesaleRequest,
  CertaintySellWholesaleDetail,
  ReportTransactionDay,
  CertaintyReport,
  NotCertaintyList,
  TransactionDayList,
  NotCertaintyRequest,
  TransactionDaySeller,
  //////////////////////////Listing Basic Data/////////////////
  FinalSharedHolder,
  AuditCompanies,
  AuditCompaniesDetail,
  AcceptanceCompanies,
  AcceptanceCompaniesDetail,
  FinalSharedHolderDetail,
  AdmissionsTeamMembers,
  AdmissionsTeamMembersDetail,
  InvestmentFunds,
  InvestmentFundsDetail,
  Users,
  UsersDtail,
  ////////////////////////////////Listing Stock/////////////////////////////
  NewListingDossier,
  DossierDetail,
  AcceptanceFiles,

  /////////////////////////////////////////////Industry/////////////////////
  InsideryStuff,
  InsideryUser,
  SurveySubmitInfo,
  Patient,
  PatientDetail,
  CompanyDetail,
  Company,
  Appointment,
  AppointmentDetail,
  Doctor,
  DoctorDetail,
  InvoiceDetail,
  GetOrder,
  HealanLayout,
  HealanDashboard,
  HealanQueue,
  HealanClinicAppointments,
  HealanClinicAppointmentDetail,
  HealanClinicPatients,
  HealanClinicDoctors,
  HealanClinicPrescriptions,
} from './imports';
import Order from '../../pages/Healan/Order';
export const cartableRoute = {
  id: 0,
  path: 'cartable',
  name: 'کارتابل کاری',
  component: Cartable,
};
export const basicDataRouts = {
  id: 2,
  path: 'operation',
  component: Outlet,
  name: 'داده های پایه',
  //hide: checkIsHide('/operation'),
  nested: [
    {
      id: 21,
      path: 'instrument-parameter',
      name: 'پارامترهای ناشر نماد',
      component: InstrumentParameter,
      //hide: checkIsHide('/operation/instrument-parameter'),
    },
    {
      id: 22,
      path: 'market-parameter',
      name: 'تغییر موقت پارامترهای بازارگردانی',
      component: MarketParameter,
      //hide: checkIsHide('/operation/market-parameter'),
    },
    {
      id: 23,
      path: 'rejection-reason',
      name: 'ثبت علت رد',
      component: RejectionReason,
      //hide: checkIsHide('/operation/rejection-reason'),
    },
    {
      id: 24,
      path: 'marketing-fund',
      name: 'صندوق بازارگردانی',
      component: MarketingFund,
      //hide: checkIsHide('/operation/marketing-fund'),
    },
    {
      id: 25,
      path: 'instrument',
      name: 'نمادها',
      component: Instrument,
      //hide: checkIsHide('/operation/instrument'),
    },
    {
      id: 26,
      path: 'quit-reason',
      name: 'ثبت علت انصراف',
      component: QuitReason,
      //hide: checkIsHide('/operation/quit-reason'),
    },
    {
      id: 27,
      path: 'extending-time',
      name: 'مهلت تمدید',
      component: ExtendingTime,
      //hide: checkIsHide('/operation/extending-time'),
    },
  ],
};
export const newTools = {
  id: 3,
  path: 'instrument',
  component: Outlet,
  name: 'ابزارهای نوین',
  //hide: checkIsHide('/instrument'),
  nested: [
    {
      id: 30,
      path: 'new-instrument',
      name: 'تعریف نماد',
      component: NewInstrument,
      //hide: checkIsHide('/instrument/new-instrument'),
    },
    {
      id: 31,
      path: 'instrument-list',
      name: 'فهرست نماد ها',
      component: InstrumentList,
      //hide: checkIsHide('/instrument/instrument-list'),
    },
    {
      id: 32,
      path: 'instrument-tradeOption-details',
      name: '',
      component: InstrumentTradeOptionDetails,
      //hide: true,
    },
    {
      id: 33,
      path: 'instrument-option-details',
      name: '',
      component: InstrumentOptionDetails,
      //hide: true,
    },
    {
      id: 34,
      path: 'instrument-future-details',
      name: '',
      component: InstrumentFutureDetails,
      //hide: true,
    },
    {
      id: 35,
      path: 'instrument-debit-details',
      name: '',
      component: InstrumentDebitDetails,
      //hide: true,
    },
    {
      id: 36,
      path: 'instrument-fund-details',
      name: '',
      component: InstrumentFundDetails,
      //hide: true,
    },
  ],
};
export const marketMaker = {
  id: 4,
  path: 'stock',
  component: Outlet,
  name: 'بازارگردانی',
  //hide: checkIsHide('/market-maker'),
  nested: [
    {
      id: 41,
      path: 'request-start-marketing',
      name: 'درخواست شروع بازارگردانی',
      component: RequestStartMarketing,
      //hide: checkIsHide('/stock/request-start-marketing'),
    },
    {
      id: 42,
      path: 'request-cancel-continue-marketing',
      name: 'درخواست تمدید/انصراف بازارگردانی',
      component: Cartable,
      //hide: checkIsHide('/stock/request-cancel-continue-marketing'),
    },
    {
      id: 43,
      path: 'request-change-parameter',
      name: 'تغییر پارامترهای بازارگردانی',
      component: RequestChangeParameter,
      //hide: checkIsHide('/stock/request-change-parameter'),
    },
    {
      id: 44,
      path: 'request-change-broker',
      name: 'تغییر کارگزار',
      component: RequestChangeBroker,
      //hide: checkIsHide('/stock/request-change-broker'),
    },
    {
      id: 431,
      path: 'change-parameter-details',
      name: 'جزئیات درخواست تغییر پارامترهای بازارگردانی',
      component: RequestChangeParameterDetails,
      //hide: true,
    },
    {
      id: 432,
      path: 'request-change-parameter-disapprove',
      name: 'عدم تایید تغییر پارامترهای بازارگردانی',
      component: RequestChangeParameter,
      //hide: true,
    },
    {
      id: 434,
      path: 'change-parameter-deadline',
      name: 'تعیین مهلت درخواست تغییر پارامتر',
      component: RequestChangeParameterDetails,
      //hide: true,
    },
    {
      id: 435,
      path: 'change-parameter-download-announcement',
      name: 'دانلود اطلاعیه تغییر پارامتر',
      component: RequestChangeParameterDetails,
      //hide: true,
    },
    {
      id: 441,
      path: 'request-change-broker-disapprove',
      name: 'عدم تایید شروع درخواست تغییر کارگزار',
      component: RequestChangeBroker,
      //hide: true,
    },
    {
      id: 442,
      path: 'request-change-broker-details',
      name: 'جزئیات درخواست تغییر کارگزار',
      component: RequestChangeBrokerDetails,
      //hide: true,
    },
    {
      id: 443,
      path: 'request-change-broker-end',
      name: 'اختتام درخواست تغییر کارگزار',
      component: RequestChangeBrokerDetails,
      //hide: true,
    },
  ],
};

export const transferStock = {
  id: 5,
  path: 'stock',
  component: Outlet,
  name: 'خارج از ساعت',
  //hide: checkIsHide('/transfer-stock'),
  nested: [
    {
      id: 51,
      path: 'request-transfer-stock',
      name: 'درخواست معاملات خارج از ساعت',
      component: RequestTransferStock,
      //hide: checkIsHide('/stock/request-transfer-stock'),
    },
    {
      id: 511,
      path: 'request-details-transfer-stock',
      name: 'جزئیات درخواست خارج از ساعت',
      component: RequestDetailsTransferStock,
      //hide: true,
    },
    {
      id: 512,
      path: 'set-deadline-transfer-stock',
      name: 'مهلت ارسال مدارک تکمیلی خارج از ساعت',
      component: SetDeadLineTransferStock,
      //hide: true,
    },
    {
      id: 513,
      path: 'send-attachment-transfer-stock',
      name: 'ارسال مدارک تکمیلی خارج از ساعت',
      component: SendAttachmentTransferStock,
      //hide: true,
    },
    {
      id: 514,
      path: 'confirm-attachment-transfer-stock',
      name: 'بررسی و تایید مدارک تکمیلی',
      component: RequestDetailsTransferStock,
      //hide: true,
    },
  ],
};
export const initialSupply = {
  id: 6,
  path: 'stock',
  component: Outlet,
  name: 'عرضه اولیه',
  //hide: checkIsHide('/initial-supply'),
  nested: [
    {
      id: 61,
      path: 'request-initial-supply',
      name: 'درخواست عرضه اولیه',
      component: InitialSupplyTransaction,
      //hide: checkIsHide('/stock/request-initial-supply'),
    },
    {
      id: 611,
      path: 'request-details-initial-supply',
      name: 'جزئیات درخواست عرضه اولیه',
      component: InitialSupplyRequestDetails,
      //hide: true,
    },
    {
      id: 612,
      path: 'download-announcement-initial-supply',
      name: 'دانلود اطلاعیه عرضه اولیه',
      component: InitialSupplyRequestDetails,
      //hide: true,
    },
  ],
};
export const block = {
  id: 7,
  path: 'stock',
  component: Outlet,
  name: 'بلوک',
  //hide: checkIsHide('/block'),
  nested: [
    {
      id: 71,
      path: 'request-block',
      name: 'درخواست معامله بلوک',
      component: BlockTransaction,
      //hide: checkIsHide('/stock/request-block'),
    },
    {
      id: 711,
      path: 'preview-block',
      name: 'مشاهده بلوک',
      component: BlockTransactionPreview,
      //hide: true,
    },
    {
      id: 712,
      path: 'request-tracking-block',
      name: 'پیگیری درخواست بلوک',
      component: BlockRequestTracking,
      //hide: true,
    },
    {
      id: 713,
      path: 'request-details-block',
      name: 'جزئیات درخواست بلوک',
      component: BlockRequestDetails,
      //hide: true,
    },
    {
      id: 714,
      path: 'change-status-block',
      name: 'تغییر وضعیت معامله بلوک',
      component: BlockChangeStatus,
      //hide: true,
    },
  ],
};
export const stockMarket = {
  id: 8,
  path: 'stock',
  component: Outlet,
  name: 'عمده',
  //hide: checkIsHide('/stock'),
  nested: [
    {
      id: 81,
      path: 'cartable',
      name: 'کارتابل کاری',
      component: Cartable,
      //hide: true,
    },
    {
      id: 83,
      path: 'request-buy-wholesale-adlist',
      name: 'لیست آگهی عرضه عمده',
      component: RequestBuyAdList,
      //hide: checkIsHide('/stock/request-buy-wholesale-adlist'),
    },
    {
      id: 82,
      path: 'request-sell-wholesale',
      name: 'درخواست عرضه عمده',
      component: WholesaleCashRequest,
      //hide: checkIsHide('/stock/request-sell-wholesale'),
    },
    {
      id: 85,
      path: 'cancel-request-sell-wholesale-list',
      name: 'انصراف از عرضه عمده',
      component: CancelRequestSellWholesaleList,
      //hide: checkIsHide('/stock/cancel-request-sell-wholesale-list'),
    },
    {
      id: 84,
      path: 'cancel-request-buy-wholesale-list',
      name: 'انصراف از خرید عمده/عودت وجه',
      component: CancelRequestBuyWholesaleList,
      //hide: checkIsHide('/stock/cancel-request-buy-wholesale-list'),
    },
    {
      id: 86,
      path: 'certainty-sell-wholesale-list',
      name: 'قطعیت معامله عمده',
      component: CertaintySellWholesaleList,
      //hide: checkIsHide('/stock/certainty-sell-wholesale-list'),
    },
    {
      id: 821,
      path: 'request-tracking-sell-wholesale',
      name: 'پیگیری درخواست فروش عمده',
      component: WholeSaleSellRequestTracking,
      //hide: true,
    },
    {
      id: 822,
      path: 'request-details-expert-sell-wholesale',
      name: 'جزئیات درخواست فروش عمده کارشناس',
      component: WholeSaleSellRequestDetailsExpert,
      //hide: true,
    },
    {
      id: 823,
      path: 'request-details-sell-wholesale',
      name: 'جزئیات درخواست فروش عمده',
      component: WholeSaleSellRequestDetails,
      //hide: true,
    },
    {
      id: 824,
      path: 'publish-notice-sell-wholesale',
      name: 'انتشار اطلاعیه فروش عمده',
      component: WholeSaleSellRequestDetails,
      //hide: true,
    },
    {
      id: 825,
      path: 'request-details-deputy-sell-wholesale',
      name: 'جزئیات درخواست فروش عمده معاون',
      component: WholeSaleSellRequestDetails,
      //hide: true,
    },
    {
      id: 831,
      path: 'request-buy-wholesale',
      name: 'درخواست خرید عمده',
      component: RequestBuyWholeSale,
      //hide: true,
    },
    {
      id: 832,
      path: 'request-detail-buy-wholesale',
      name: 'جزئیات درخواست خرید عمده',
      component: RequestDetailBuyWholeSale,
      //hide: true,
    },
    {
      id: 833,
      path: 'request-detail-buy-deputy',
      name: 'جزئیات درخواست معاونت',
      component: RequestDetailBuyWholeSale,
      //hide: true,
    },
    {
      id: 834,
      path: 'request-detail-buy-upload-doc',
      name: 'جزئیات درخواست اپلود مکاتبات',
      component: RequestDetailBuyWholeSale,
      //hide: true,
    },
    {
      id: 835,
      path: 'request-detail-buy-wholesale-without-enter-data',
      name: 'جزئیات درخواست خرید عمده بدون ورود اطلاعات',
      component: RequestDetailBuyWholeSale,
      //hide: true,
    },
    {
      id: 836,
      path: 'request-detail-buy-wholesale-fyi',
      name: 'جزئیات درخواست خرید عمده جهت اطلاع کارگزار',
      component: RequestDetailBuyWholeSale,
      //hide: true,
    },
    {
      id: 841,
      path: 'cancel-request-buy-wholesale',
      name: 'درخواست عودت وجه خرید عمده',
      component: RequestCancelBuyWholesale,
      //hide: true,
    },
    {
      id: 842,
      path: 'cancel-request-buy-wholesale-details',
      name: 'جزئیات درخواست عودت وجه خرید عمده',
      component: RequestDetailCancelBuyWholesale,
      //hide: true,
    },
    {
      id: 843,
      path: 'cancel-request-buy-wholesale-upload-doc',
      name: 'اپلود مکاتبات عودت وجه خرید عمده',
      component: RequestDetailCancelBuyWholesale,
      //hide: true,
    },
    {
      id: 844,
      path: 'cancel-request-buy-wholesale-fyi',
      name: 'جزئیات عودت وجه خرید عمده جهت اطلاع کارگزار',
      component: RequestDetailCancelBuyWholesale,
      //hide: true,
    },
    {
      id: 851,
      path: 'cancel-request-sell-wholesale',
      name: 'درخواست انصراف از فروش عمده',
      component: CancelRequestSellWholesale,
      //hide: true,
    },
    {
      id: 852,
      path: 'cancel-request-sell-wholesale-details',
      name: 'جزئیات درخواست انصراف از فروش عمده',
      component: CancelRequestDetailSellWholesale,
      //hide: true,
    },
    {
      id: 853,
      path: 'cancel-request-sell-wholesale-upload-doc',
      name: 'آپلود مکاتبات انصراف از فروش عمده',
      component: CancelRequestDetailSellWholesale,
      //hide: true,
    },
    {
      id: 854,
      path: 'cancel-request-sell-wholesale-fyi',
      name: 'جزئیات درخواست انصراف از فروش عمده جهت اطلاع کارگزار',
      component: CancelRequestDetailSellWholesale,
      //hide: true,
    },
    {
      id: 861,
      path: 'certainty-sell-wholesale-request',
      name: 'درخواست قطعیت معامله فروش',
      component: CertaintySellWholesaleRequest,
      //hide: true,
    },
    {
      id: 862,
      path: 'certainty-sell-wholesale-details',
      name: 'جزئیات درخواست قطعیت معامله فروش',
      component: CertaintySellWholesaleDetail,
      //hide: true,
    },
    {
      id: 863,
      path: 'certainty-sell-wholesale-upload-doc',
      name: 'اپلود مکاتبات قطعیت معامله فروش',
      component: CertaintySellWholesaleDetail,
      //hide: true,
    },
    {
      id: 864,
      path: 'certainty-sell-wholesale-fyi',
      name: 'جهت اطلاع قطعیت معامله فروش',
      component: CertaintySellWholesaleDetail,
      //hide: true,
    },
  ],
};

export const reportRouts = {
  id: 9,
  path: 'reports',
  component: Outlet,
  name: 'گزارشات',
  //hide: checkIsHide('/reports'),
  nested: [
    // {
    //   id: 161,
    //   path: 'parameter-reports',
    //   name: 'ناشر و پارامترهای بازارگردانی',
    //   component: ParameterReport,
    // },
    // {
    //   id: 162,
    //   path: 'instrument-view',
    //   name: 'دیده بان نماد',
    //   component: InstrumentView,
    // },
    {
      id: 91,
      path: 'request-report',
      name: 'درخواست ها',
      component: RequestReport,
      //hide: checkIsHide('/reports/request-report'),
    },
    {
      id: 92,
      path: 'market-maker-parameter',
      name: 'پارامتر بازارگردانی',
      component: ParameterReports,
      //hide: checkIsHide('/reports/market-maker-parameter'),
    },
    {
      id: 93,
      path: 'market-maker-instrument',
      name: 'نماد دارای بازارگردان',
      component: InstrumentMarketMaker,
      //hide: checkIsHide('/reports/market-maker-instrument'),
    },
    {
      id: 94,
      path: 'market-maker-change-parameter',
      name: 'تغییر پارامتر بازارگردانی',
      component: ChangeParameterReport,
      //hide: checkIsHide('/reports/market-maker-change-parameter'),
    },
    {
      id: 95,
      path: 'transaction-day',
      name: 'روز معامله-عدم ارسال قطعیت معامله',
      component: ReportTransactionDay,
      //hide: checkIsHide('/reports/transaction-day'),
    },
    {
      id: 96,
      path: 'certainty-deadline',
      name: 'عدم ارسال قطعیت معامله پس از مهلت',
      component: CertaintyReport,
      //hide: checkIsHide('/reports/certainty-deadline'),
    },
  ],
};
export const userRouts = {
  id: 10,
  path: 'manage',
  component: Outlet,
  name: 'تنظیمات',
  //hide: checkIsHide('/manage'),
  nested: [
    {
      id: 101,
      path: 'user',
      component: UserManagement,
      name: 'مدیریت کاربران',
      //hide: checkIsHide('/manage/user'),
    },
    {
      id: 102,
      path: 'access',
      component: ManageRole,
      name: 'مدیریت دسترسی',
      //hide: checkIsHide('/manage/access'),
    },
  ],
};
export const transactionManagement = {
  id: 11,
  path: 'transaction',
  component: Outlet,
  name: 'مدیریت معاملات',
  //hide: checkIsHide('/transaction'),
  nested: [
    {
      id: 111,
      path: 'not-certainty-list',
      name: 'عدم قطعیت معامله فروش',
      component: NotCertaintyList,
      //hide: checkIsHide('/transaction/not-certainty-list'),
    },
    {
      id: 112,
      path: 'transaction-day-list',
      name: 'روز معامله',
      component: TransactionDayList,
      //hide: checkIsHide('/transaction/transaction-day-list'),
    },
    {
      id: 1111,
      path: 'not-certainty-request',
      name: 'درخواست عدم قطعیت معامله فروش',
      component: NotCertaintyRequest,
      //hide: true,
    },
    {
      id: 1121,
      path: 'transaction-day-seller',
      name: 'متقاضیان روز معامله',
      component: TransactionDaySeller,
      //hide: true,
    },
  ],
};
export const othersRouts = [
  {
    id: 100,
    path: 'cartable',
    component: Cartable,
    name: '',
    //hide: true,
  },
  {
    id: 101,
    path: 'callback',
    component: CallbackPage,
    name: '',
    //hide: true,
  },
  {
    id: 102,
    path: 'request-detail',
    component: RequestDetails,
    name: '',
    //hide: true,
  },
  {
    id: 103,
    path: 'request-edit',
    name: '',
    component: RequestStartMarketing,
    //hide: true,
  },
  {
    id: 104,
    path: 'request-extending',
    name: '',
    component: RequestStartMarketing,
    //hide: true,
  },
  {
    id: 105,
    path: 'extending-request-detail',
    component: RequestDetails,
    name: '',
    //hide: true,
  },
  {
    id: 106,
    path: 'extending-request-edit',
    name: '',
    component: RequestStartMarketing,
    //hide: true,
  },
  // {
  //   id: 11,
  //   path: 'InstructionInfo',
  //   name: 'فرم ها و دستورالعمل ها',
  //   component: InstructionInfo,
  // },
  {
    id: 107,
    path: 'profile',
    name: '',
    component: Profile,
    //hide: true,
  },
  {
    id: 108,
    path: 'cancel-request',
    name: '',
    component: CancelRequest,
    //hide: true,
  },
  {
    id: 109,
    path: 'profile-detail',
    name: '',
    component: ProfileDetail,
    //hide: true,
  },
  {
    id: 110,
    path: 'access-request-detail',
    name: '',
    component: AccessRequestDetail,
    //hide: true,
  },
  {
    id: 111,
    path: 'request-orderquit-detail',
    component: RequestDetails,
    name: '',
    //hide: true,
  },
  {
    id: 112,
    path: 'request-orderquit-edit',
    name: '',
    component: CancelRequest,
    //hide: true,
  },
  {
    id: 113,
    path: 'messages-list',
    name: 'پیام ها',
    component: MessagesList,
    //hide: true,
  },
];
////////////////////////////Healan Clinic/////////////////////////////////
export const healanClinic = {
  id: 200,
  path: 'healan',
  component: HealanLayout,
  name: 'مدیریت کلینیک Healan',
  nested: [
    {
      id: 2001,
      path: '',
      name: 'داشبورد',
      component: HealanDashboard,
    },
    {
      id: 2002,
      path: 'queue',
      name: 'صف انتظار',
      component: HealanQueue,
    },
    {
      id: 2003,
      path: 'appointments',
      name: 'پذیرش و نوبت',
      component: HealanClinicAppointments,
    },
    {
      id: 20031,
      path: 'appointments/:id',
      name: 'جزئیات نوبت',
      component: HealanClinicAppointmentDetail,
      hide: true,
    },
    {
      id: 2004,
      path: 'patients',
      name: 'بیماران',
      component: HealanClinicPatients,
    },
    {
      id: 2005,
      path: 'doctors',
      name: 'پزشکان',
      component: HealanClinicDoctors,
    },
    {
      id: 2006,
      path: 'prescriptions',
      name: 'نسخه‌ها',
      component: HealanClinicPrescriptions,
    },
  ],
};
////////////////////////////Listing/////////////////////////////////
export const listingBasicData = {
  id: 12,
  path: 'listing-basicdata',
  component: Outlet,
  name: 'داده‌های پایه پذیرش',
  //hide: checkIsHide('/block'),
  nested: [
    {
      id: 1200,
      path: 'users',
      name: 'کاربران',
      component: Users,
      //hide: checkIsHide('/stock/request-block'),
    },
    {
      id: 12000,
      path: 'users-profile',
      name: 'پروفایل کاربران ',
      component: UsersDtail,
      hide: true,
    },
    {
      id: 1201,
      path: 'patients',
      name: 'ثبت بیمار',
      component: Patient,
      //hide: checkIsHide('/stock/request-block'),
    },
    {
      id: 12010,
      path: 'patient-detail',
      name: 'جزئیات بیمار ',
      component: PatientDetail,
      hide: true,
    },
    {
      id: 1202,
      path: 'companies',
      name: 'شرکت',
      component: Company,
    },
    {
      id: 12020,
      path: 'company-detail',
      name: 'جزئیات شرکت',
      component: CompanyDetail,
      hide: true,
    },
    {
      id: 1203,
      path: 'appointment',
      name: 'پذیرش بیمار',
      component: Appointment,
      //hide: checkIsHide('/stock/request-block'),
    },
    {
      id: 12030,
      path: 'appointment-detail',
      name: 'جزئیات پذیرش بیمار',
      component: AppointmentDetail,
      hide: true,
    },
    {
      id: 1204,
      path: 'doctors',
      name: 'ثبت پزشک',
      component: Doctor,
      //hide: checkIsHide('/stock/request-block'),
    },
    {
      id: 12040,
      path: 'doctor-detail',
      name: 'جزئیات پزشک',
      component: DoctorDetail,
      hide: true,
    },
    {
      id: 1205,
      path: 'getInvoice',
      name: 'جزئیات هزینه نوبت',
      component: InvoiceDetail,
      //hide: checkIsHide('/stock/request-block'),
    },
    {
      id: 1206,
      path: 'order',
      name: 'لیست بیمارن',
      component: Order,
      //hide: checkIsHide('/stock/request-block'),
    },
    {
      id: 1207,
      path: 'getOrder',
      name: 'جزئیات نسخه',
      component: GetOrder,
      hide: true,
    },
    {
      id: 12050,
      path: 'investment-funds-detail',
      name: 'جزئیات صندوق های سرمایه گذاری',
      component: InvestmentFundsDetail,
      hide: true,
    },

  ],
};

export const listingStockAcceptance = {
  id: 13,
  path: 'listing-stock',
  component: Outlet,
  name: 'پذیرش سهام',
  //hide: checkIsHide('/block'),
  nested: [
    {
      id: 1300,
      path: 'new-dossier',
      name: 'ثبت پرونده جدید',
      component: NewListingDossier,
      hide: false,
    },
    {
      id: 13000,
      path: 'dossier-detail',
      name: 'جزئیات پرونده',
      component: DossierDetail,
      hide: true,
    },
    {
      id: 1301,
      path: 'acceptance-dossieres',
      name: 'پرونده‌های پذیرش سهام',
      component: AcceptanceFiles,
      hide: false,
    },
  ],
};

////////////////////////////Insidery/////////////////////////////////

export const insidery = {
  id: 14,
  path: 'insidery',
  component: Outlet,
  name: 'اطلاعات نهانی',
  //hide: checkIsHide('/insidery'),
  nested: [
    {
      id: 1400,
      path: 'insidery-user',
      name: 'ثبت اطلاعات کاربران',
      component: InsideryUser,
      hide: false,
    },
    {
      id: 14000,
      path: 'insidery-staff',
      name: 'خود اظهاری پرسنل',
      component: InsideryStuff,
      hide: false,
    },
  ],
};
/////////////////////////////////corporate survey////////////////////////////////
export const corporateSurvey = {
  id: 15,
  path: 'survey',
  component: Outlet,
  name: 'حاکمیت شرکتی',
  //hide: checkIsHide('/block'),
  nested: [
    {
      id: 1500,
      path: 'submit-info',
      name: 'ثبت اطلاعات',
      component: SurveySubmitInfo,
      hide: false,
    },
  ],
};
