// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkFlow.Infrastructure.Persistence;

#nullable disable

namespace WorkFlow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102100227_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkFlow.Domain.Entities.Form", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("Int");

                    b.Property<string>("BackwardClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FormStateId")
                        .HasColumnType("int");

                    b.Property<string>("FormUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ForwardClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FormId");

                    b.ToTable("Form", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Fund", b =>
                {
                    b.Property<Guid>("FundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid?>("BrokerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FundId");

                    b.ToTable("Fund", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExtraInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FundId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeny")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OrderParentId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<byte>("OrderStatusId")
                        .HasColumnType("TinyInt");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("1000000");

                    b.Property<Guid?>("WorkFlowUserId")
                        .HasColumnType("UniqueIdentifier");

                    b.HasKey("OrderId");

                    b.HasIndex("FundId");

                    b.HasIndex("OrderParentId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("WorkFlowUserId");

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.OrderComment", b =>
                {
                    b.Property<Guid>("OrderCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("DateTime");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("Bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid>("WorkFlowGuidId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid>("WorkFlowUserId")
                        .HasColumnType("UniqueIdentifier");

                    b.HasKey("OrderCommentId");

                    b.HasIndex("OrderId");

                    b.HasIndex("WorkFlowGuidId");

                    b.HasIndex("WorkFlowUserId");

                    b.ToTable("OrderComment", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<byte>("OrderStatusId")
                        .HasColumnType("TinyInt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderStatusId");

                    b.ToTable("OrderStatus", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowArchive", b =>
                {
                    b.Property<Guid>("WorkFlowArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<DateTime>("WorkFlowArchiveDate")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("WorkFlowDate")
                        .HasColumnType("DateTime");

                    b.Property<Guid>("WorkFlowGuidId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid>("WorkFlowItemId")
                        .HasColumnType("UniqueIdentifier");

                    b.HasKey("WorkFlowArchiveId");

                    b.HasIndex("OrderId");

                    b.HasIndex("WorkFlowGuidId");

                    b.ToTable("WorkFlowArchive", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowGuide", b =>
                {
                    b.Property<Guid>("WorkFlowGuideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<int>("FormId")
                        .HasColumnType("Int");

                    b.Property<byte?>("OrderStatusId")
                        .HasColumnType("TinyInt");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<int>("ReceiverGroupId")
                        .HasColumnType("Int");

                    b.Property<int>("SenderGroupId")
                        .HasColumnType("Int");

                    b.Property<int>("Weight")
                        .HasColumnType("Int");

                    b.Property<int>("WorkFlowTypeId")
                        .HasColumnType("Int");

                    b.HasKey("WorkFlowGuideId");

                    b.HasIndex("FormId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ReceiverGroupId");

                    b.HasIndex("SenderGroupId");

                    b.HasIndex("WorkFlowTypeId");

                    b.ToTable("WorkFlowGuide", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowItem", b =>
                {
                    b.Property<Guid>("WorkFlowItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<bool>("HasObserved")
                        .HasColumnType("Bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<DateTime>("WorkFlowDate")
                        .HasColumnType("DateTime");

                    b.Property<Guid>("WorkFlowGuideId")
                        .HasColumnType("UniqueIdentifier");

                    b.HasKey("WorkFlowItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("WorkFlowGuideId");

                    b.ToTable("WorkFlowItem", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowStatusGuide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuideId")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("GuideId");

                    b.Property<byte>("OrderStatusId")
                        .HasColumnType("TinyInt")
                        .HasColumnName("OrderStatusId");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("WorkFlowStatusGuide", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowType", b =>
                {
                    b.Property<int>("WorkFlowTypeId")
                        .HasColumnType("Int");

                    b.Property<int?>("RecordFormId")
                        .HasColumnType("Int");

                    b.Property<string>("WorkFlowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WorkFlowTypeId");

                    b.HasIndex("RecordFormId");

                    b.ToTable("WorkFlowType", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowUser", b =>
                {
                    b.Property<Guid>("WorkFlowUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid?>("BrokerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("FundId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid?>("IdentityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("Bit");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WorkFlowUserGroupId")
                        .HasColumnType("Int");

                    b.HasKey("WorkFlowUserId");

                    b.HasIndex("FundId");

                    b.HasIndex("WorkFlowUserGroupId");

                    b.ToTable("WorkFlowUser", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowUserGroup", b =>
                {
                    b.Property<int>("WorkFlowUserGroupId")
                        .HasColumnType("Int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WorkFlowUserGroupId");

                    b.ToTable("WorkFlowUserGroup", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Order", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.Fund", "Fund")
                        .WithMany("Orders")
                        .HasForeignKey("FundId");

                    b.HasOne("WorkFlow.Domain.Entities.Order", "ParentOrder")
                        .WithMany("OrderChilds")
                        .HasForeignKey("OrderParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkFlow.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowUser", "WorkFlowUser")
                        .WithMany("Orders")
                        .HasForeignKey("WorkFlowUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fund");

                    b.Navigation("OrderStatus");

                    b.Navigation("ParentOrder");

                    b.Navigation("WorkFlowUser");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.OrderComment", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.Order", "Order")
                        .WithMany("OrderComments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowGuide", "WorkFlowGuide")
                        .WithMany("OrderComments")
                        .HasForeignKey("WorkFlowGuidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowUser", "WorkFlowUser")
                        .WithMany("OrderComments")
                        .HasForeignKey("WorkFlowUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("WorkFlowGuide");

                    b.Navigation("WorkFlowUser");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowArchive", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.Order", "Order")
                        .WithMany("WorkFlowArchives")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowGuide", "WorkFlowGuide")
                        .WithMany("WorkFlowArchives")
                        .HasForeignKey("WorkFlowGuidId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("WorkFlowGuide");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowGuide", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.Form", "Form")
                        .WithMany("WorkFlowGuides")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkFlow.Domain.Entities.OrderStatus", null)
                        .WithMany("WorkFlowGuides")
                        .HasForeignKey("OrderStatusId");

                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowGuide", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowUserGroup", "WorkFlowUserGroupReceiver")
                        .WithMany("WorkFlowGuideReceivers")
                        .HasForeignKey("ReceiverGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowUserGroup", "WorkFlowUserGroupSender")
                        .WithMany("WorkFlowGuideSenders")
                        .HasForeignKey("SenderGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowType", "WorkFlowType")
                        .WithMany("WorkFlowGuides")
                        .HasForeignKey("WorkFlowTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Parent");

                    b.Navigation("WorkFlowType");

                    b.Navigation("WorkFlowUserGroupReceiver");

                    b.Navigation("WorkFlowUserGroupSender");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowItem", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.Order", "Order")
                        .WithMany("WorkFlowItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowGuide", "WorkFlowGuide")
                        .WithMany("WorkFlowItems")
                        .HasForeignKey("WorkFlowGuideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("WorkFlowGuide");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowStatusGuide", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowGuide", "WorkFlowGuide")
                        .WithMany("WorkFlowStatusGuides")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlow.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany("WorkFlowStatusGuides")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("WorkFlowGuide");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowType", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.Form", "Form")
                        .WithMany("WorkFlowTypes")
                        .HasForeignKey("RecordFormId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Form");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowUser", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.Fund", "Fund")
                        .WithMany("WorkFlowUsers")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkFlow.Domain.Entities.WorkFlowUserGroup", "WorkFlowUserGroup")
                        .WithMany("WorkFlowUsers")
                        .HasForeignKey("WorkFlowUserGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("WorkFlowUserGroup");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Form", b =>
                {
                    b.Navigation("WorkFlowGuides");

                    b.Navigation("WorkFlowTypes");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Fund", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("WorkFlowUsers");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderChilds");

                    b.Navigation("OrderComments");

                    b.Navigation("WorkFlowArchives");

                    b.Navigation("WorkFlowItems");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("WorkFlowGuides");

                    b.Navigation("WorkFlowStatusGuides");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowGuide", b =>
                {
                    b.Navigation("Childs");

                    b.Navigation("OrderComments");

                    b.Navigation("WorkFlowArchives");

                    b.Navigation("WorkFlowItems");

                    b.Navigation("WorkFlowStatusGuides");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowType", b =>
                {
                    b.Navigation("WorkFlowGuides");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowUser", b =>
                {
                    b.Navigation("OrderComments");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.WorkFlowUserGroup", b =>
                {
                    b.Navigation("WorkFlowGuideReceivers");

                    b.Navigation("WorkFlowGuideSenders");

                    b.Navigation("WorkFlowUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
