<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TSEAI.Application/TSEAI.Application.csproj" />
    <ProjectReference Include="../../../Shared/TSEAI.Shared.Application/TSEAI.Shared.Application.csproj" />
  </ItemGroup>
</Project>
