// <auto-generated />
using System;
using CaptchaProvider.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaptchaProvider.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210113336_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaptchaProvider.Domain.Entities.CaptchaInfo", b =>
                {
                    b.Property<Guid>("CaptchaInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RequestIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("SmallDateTime");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CaptchaInfoId");

                    b.ToTable("CaptchaInfo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
