"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ContractConversation,ContractConversationListItem,ContractGroup,ContractSourceOption,OrganizationParty,downloadContractDraftFile,getContractConversation,listContractCatalog,listContractConversations,listContractSourceOptions,reviewContractDraft,saveContractCatalog,sendContractConversationMessage,startContractConversation} from "../../lib/api";
const conversationStates:Record<number,string>={1:"فعال",2:"نیازمند پاسخ",3:"در بازبینی",4:"نهایی‌شده",5:"لغوشده"};
const draftStates:Record<number,string>={1:"تأیید درخواست‌کننده",2:"تأیید کارشناس",3:"تأیید مدیر",4:"نهایی",5:"ردشده"};
export default function ContractGenerationPage(){
 const [items,setItems]=useState<ContractConversationListItem[]>([]),[parties,setParties]=useState<OrganizationParty[]>([]),[groups,setGroups]=useState<ContractGroup[]>([]);const [current,setCurrent]=useState<ContractConversation>();
 const [sourceOptions,setSourceOptions]=useState<ContractSourceOption[]>([]),[selectedSources,setSelectedSources]=useState<string[]>([]);
 const [partyId,setPartyId]=useState(""),[groupId,setGroupId]=useState(""),[year,setYear]=useState(1405),[subject,setSubject]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [newPartyName,setNewPartyName]=useState("");
 const latest=current?.drafts[0],unresolved=useMemo(()=>current?.clarifications.filter(x=>!x.isAnswered)??[],[current]);
 async function load(){const [h,p,g,s]=await Promise.all([listContractConversations(),listContractCatalog<OrganizationParty>("parties",1,100),listContractCatalog<ContractGroup>("groups",1,100),listContractSourceOptions()]);setItems(h);setParties(p.items.filter(x=>x.isActive));setGroups(g.items.filter(x=>x.isActive));setSourceOptions(s);}
 useEffect(()=>{load().catch(e=>setNotice(String(e)));},[]);
 async function run(action:()=>Promise<ContractConversation>){setBusy(true);setNotice("");try{setCurrent(await action());setMessage("");await load();}catch(e){setNotice(e instanceof Error?e.message:"خطای پیش‌بینی‌نشده");}finally{setBusy(false);}}
 function start(e:FormEvent){e.preventDefault();void run(()=>startContractConversation({organizationPartyId:partyId,primaryContractGroupId:groupId,contractYear:year,subject,message,additionalSourceContractIds:selectedSources}));}
 function send(e:FormEvent){e.preventDefault();if(current&&message.trim())void run(()=>sendContractConversationMessage(current.id,message));}
 async function open(id:string){setBusy(true);try{setCurrent(await getContractConversation(id));}finally{setBusy(false);}}
 function decide(approved:boolean){if(!current||!latest)return;const stage=latest.approvalStatus===1?"requester":latest.approvalStatus===2?"expert":"manager";void run(()=>reviewContractDraft(current.id,latest.id,stage,approved));}
 async function openOutput(format:"docx"|"pdf"){if(!current||!latest)return;try{const blob=await downloadContractDraftFile(current.id,latest.id,format);const url=URL.createObjectURL(blob);if(format==="pdf")window.open(url,"_blank","noopener,noreferrer");else{const a=document.createElement("a");a.href=url;a.download=`contract-draft-v${latest.versionNumber}.docx`;a.click();}window.setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){setNotice(e instanceof Error?e.message:"دریافت فایل انجام نشد.");}}
 async function createParty(){if(!newPartyName.trim())return;setBusy(true);try{const party=await saveContractCatalog<OrganizationParty>("parties",{name:newPartyName,nationalIdentifier:null,representativeName:null,contactInfo:null,isActive:true});setParties(x=>[...x,party]);setPartyId(party.id);setNewPartyName("");setNotice("طرف قرارداد ثبت و انتخاب شد.");}catch(e){setNotice(e instanceof Error?e.message:"مجوز ثبت طرف قرارداد وجود ندارد.");}finally{setBusy(false);}}
 return <main className="conversation-page"><header className="conversation-header"><div><span>مدیریت هوشمند قراردادها</span><h1>دستیار تولید قرارداد</h1><p>تولید نسخه‌دار بر اساس آخرین مرجع نهایی و قالب مؤثر گروه قرارداد</p></div><a href="/">بازگشت به داشبورد</a></header><section className="conversation-layout">
 <aside className="conversation-history panel"><h2>گفت‌وگوهای من</h2>{items.length===0&&<p className="conversation-empty">هنوز گفت‌وگویی ثبت نشده است.</p>}{items.map(x=><button key={x.id} className={current?.id===x.id?"active":""} onClick={()=>void open(x.id)}><strong>{x.title}</strong><span>{x.groupName} · {x.draftCount} پیش‌نویس</span><b>{conversationStates[x.status]}</b></button>)}</aside>
 <section className="conversation-main panel">{!current?<form className="conversation-start" onSubmit={start}><h2>درخواست جدید</h2><p>طرف قرارداد و گروه اصلی را تعیین کنید؛ مرجع و قالب به‌صورت هوشمند انتخاب می‌شوند.</p><div className="form-grid">
 <label className="field"><span>طرف قرارداد</span><select required value={partyId} onChange={e=>setPartyId(e.target.value)}><option value="">انتخاب کنید</option>{parties.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label className="field inline-party"><span>شرکت در فهرست نیست؟</span><span><input value={newPartyName} onChange={e=>setNewPartyName(e.target.value)} placeholder="نام شرکت جدید"/><button type="button" disabled={busy||!newPartyName.trim()} onClick={()=>void createParty()}>ثبت و انتخاب</button></span></label>
 <label className="field"><span>گروه اصلی قرارداد</span><select required value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">انتخاب کنید</option>{groups.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label className="field"><span>سال قرارداد</span><input required min={1300} max={1600} type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/></label><label className="field"><span>موضوع قرارداد</span><input required value={subject} onChange={e=>setSubject(e.target.value)}/></label>
 <label className="field full"><span>درخواست شما</span><textarea required value={message} onChange={e=>setMessage(e.target.value)} placeholder="مثلاً قرارداد پشتیبانی سال ۱۴۰۵ را بر اساس آخرین قرارداد با ۲۵ درصد افزایش مبلغ تنظیم کن..."/></label>
 <fieldset className="field full explicit-sources"><legend>منابع اضافی از گروه‌های دیگر (اختیاری و فقط با انتخاب صریح)</legend>{sourceOptions.filter(x=>x.primaryContractGroupId!==groupId).map(x=><label key={x.contractId}><input type="checkbox" checked={selectedSources.includes(x.contractId)} onChange={e=>setSelectedSources(v=>e.target.checked?[...v,x.contractId]:v.filter(id=>id!==x.contractId))}/><span>{x.subject} · {x.partyName} · {x.groupName} {x.contractYear?`· ${x.contractYear}`:""}</span></label>)}{!sourceOptions.some(x=>x.primaryContractGroupId!==groupId)&&<small>منبع مجاز دیگری وجود ندارد.</small>}</fieldset></div><button disabled={busy} className="primary-button">{busy?"در حال پردازش...":"شروع تولید هوشمند"}</button></form>:<>
 <header className="chat-title"><div><h2>{current.title}</h2><span>{current.partyName} · {current.groupName} · {current.contractYear}</span></div><b className={`conversation-state state-${current.status}`}>{conversationStates[current.status]}</b></header>
 <div className="chat-stream">{current.messages.map(x=><article key={x.id} className={`chat-message role-${x.role}`}><b>{x.role===1?"شما":x.role===2?"دستیار هوشمند":"سامانه"}</b><p>{x.content}</p>{x.sourceSnapshotJson&&<details><summary>مشاهده منابع پاسخ</summary><pre>{JSON.stringify(JSON.parse(x.sourceSnapshotJson),null,2)}</pre></details>}</article>)}</div>
 {unresolved.length>0&&<div className="clarification-box"><strong>پاسخ شما برای ادامه لازم است</strong>{unresolved.map(x=><p key={x.id}>{x.question}</p>)}</div>}
 {latest&&<section className="draft-card"><header><div><strong>پیش‌نویس نسخه {latest.versionNumber}</strong><span>{draftStates[latest.approvalStatus]}</span></div>{latest.finalDocumentVersionId&&<b>سند نهایی ثبت شد</b>}</header><div className="draft-output-actions"><button onClick={()=>void openOutput("pdf")}>پیش‌نمایش PDF</button><button onClick={()=>void openOutput("docx")}>دانلود DOCX</button></div><div className="draft-details"><details open><summary>تغییرات</summary><pre>{JSON.stringify(JSON.parse(latest.diffJson),null,2)}</pre></details><details><summary>تحلیل تعارض‌ها</summary><pre>{JSON.stringify(JSON.parse(latest.conflictAnalysisJson),null,2)}</pre></details><details><summary>محاسبات</summary><pre>{JSON.stringify(JSON.parse(latest.calculationSnapshotJson),null,2)}</pre></details><details><summary>منابع و استنادها</summary><pre>{JSON.stringify(JSON.parse(latest.sourceSnapshotJson),null,2)}</pre></details></div>{latest.approvalStatus<4&&<div className="review-actions"><button disabled={busy} className="approve" onClick={()=>decide(true)}>تأیید این مرحله</button><button disabled={busy} className="reject" onClick={()=>decide(false)}>رد و درخواست اصلاح</button></div>}</section>}
 {current.status!==4&&<form className="chat-compose" onSubmit={send}><textarea required value={message} onChange={e=>setMessage(e.target.value)} placeholder={unresolved.length?"پاسخ سؤال را بنویسید...":"اصلاح مورد نظر یا دستور بعدی را بنویسید..."}/><button disabled={busy}>ارسال</button></form>}</>}</section></section>{notice&&<div className="ingestion-message">{notice}</div>}</main>;
}
