"use client";
import {FormEvent,useEffect,useState} from "react";
import {ContractGroup,ContractTemplate,deleteContractTemplate,listContractCatalog,listContractTemplates,updateContractTemplate,uploadContractTemplate} from "../../../lib/api";
export default function ContractTemplatesPage(){
 const [items,setItems]=useState<ContractTemplate[]>([]),[groups,setGroups]=useState<ContractGroup[]>([]),[name,setName]=useState(""),[type,setType]=useState(""),[groupId,setGroupId]=useState(""),[year,setYear]=useState(1405),[from,setFrom]=useState(""),[to,setTo]=useState(""),[file,setFile]=useState<File|null>(null),[message,setMessage]=useState("");
 async function load(){const [t,g]=await Promise.all([listContractTemplates(),listContractCatalog<ContractGroup>("groups",1,100)]);setItems(t);setGroups(g.items)}useEffect(()=>{void load().catch(()=>setMessage("دریافت قالب‌ها انجام نشد."))},[]);
 async function submit(e:FormEvent){e.preventDefault();if(!file||!groupId)return;try{await uploadContractTemplate({name,contractType:type,file,contractGroupId:groupId,contractYear:year,effectiveFrom:from||undefined,effectiveTo:to||undefined});setFile(null);await load();setMessage("قالب ثبت شد.")}catch{setMessage("ثبت قالب انجام نشد.")}}
 return <main className="app-shell" dir="rtl"><section className="page-content"><header className="page-header"><p className="eyebrow">اطلاعات پایه</p><h1>قالب‌های نسخه‌دار قرارداد</h1></header><article className="panel"><form className="form-grid" onSubmit={e=>void submit(e)}><input placeholder="نام قالب" value={name} onChange={e=>setName(e.target.value)} required/><input placeholder="نوع قرارداد" value={type} onChange={e=>setType(e.target.value)} required/><select value={groupId} onChange={e=>setGroupId(e.target.value)} required><option value="">گروه قرارداد</option>{groups.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><input type="file" accept=".docx" onChange={e=>setFile(e.target.files?.[0]||null)} required/><button className="primary-button">ثبت نسخه جدید</button></form><p>{message}</p>{items.map(x=><div className="catalog-row" key={x.id}><span>{x.name} — نسخه {x.version} — سال {x.contractYear||"—"}</span><b>{x.isActive?"فعال":"غیرفعال"}</b><button onClick={()=>void updateContractTemplate(x.id,{name:x.name,contractType:x.contractType,description:x.description,contractGroupId:x.contractGroupId,contractYear:x.contractYear,effectiveFrom:x.effectiveFrom,effectiveTo:x.effectiveTo,isActive:!x.isActive}).then(load)}>{x.isActive?"غیرفعال‌سازی":"فعال‌سازی"}</button><button onClick={()=>window.confirm("حذف نرم شود؟")&&void deleteContractTemplate(x.id).then(load)}>حذف</button></div>)}</article></section></main>;
}
