"use client";
import {FormEvent,useEffect,useState} from "react";
import {ContractGroup,ContractTemplate,deleteContractTemplate,listContractCatalog,listContractTemplates,updateContractTemplate,uploadContractTemplate} from "../../../lib/api";
import PersianCalendar from "../../PersianCalendar";
import {formatJalaliDate} from "../../../lib/jalali";
export default function ContractTemplatesPage(){
 const [items,setItems]=useState<ContractTemplate[]>([]),[groups,setGroups]=useState<ContractGroup[]>([]),[name,setName]=useState(""),[type,setType]=useState(""),[groupId,setGroupId]=useState(""),[year,setYear]=useState(1405),[from,setFrom]=useState(""),[to,setTo]=useState(""),[file,setFile]=useState<File|null>(null),[message,setMessage]=useState("");
 async function load(){const [t,g]=await Promise.all([listContractTemplates(),listContractCatalog<ContractGroup>("groups",1,100)]);setItems(t);setGroups(g.items)}useEffect(()=>{void load().catch(()=>setMessage("دریافت قالب‌ها انجام نشد."))},[]);
 async function submit(e:FormEvent){e.preventDefault();if(!file||!groupId)return;try{await uploadContractTemplate({name,contractType:type,file,contractGroupId:groupId,contractYear:year,effectiveFrom:from||undefined,effectiveTo:to||undefined});setFile(null);await load();setMessage("قالب ثبت شد.")}catch{setMessage("ثبت قالب انجام نشد.")}}
 return <main className="app-shell" dir="rtl"><section className="page-content"><header className="page-header"><p className="eyebrow">اطلاعات پایه</p><h1>قالب‌های نسخه‌دار قرارداد</h1></header><article className="panel"><form className="form-grid" onSubmit={e=>void submit(e)}><label className="field"><span>نام قالب *</span><input placeholder="مثلاً قالب قرارداد خدماتی" value={name} onChange={e=>setName(e.target.value)} required/></label><label className="field"><span>عنوان نوع قرارداد *</span><input placeholder="مثلاً خدماتی" value={type} onChange={e=>setType(e.target.value)} required/></label><label className="field"><span>نوع قرارداد *</span><select value={groupId} onChange={e=>setGroupId(e.target.value)} required><option value="">انتخاب نوع قرارداد</option>{groups.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field"><span>سال قراردادی</span><input type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/></label><label className="field"><span>معتبر از (شمسی)</span><PersianCalendar value={from} onChange={setFrom}/></label><label className="field"><span>معتبر تا (شمسی)</span><PersianCalendar value={to} onChange={setTo}/></label><label className="field"><span>فایل Template با فرمت DOCX *</span><input type="file" accept=".docx" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label><button className="primary-button">ثبت نسخه جدید</button></form><p>{message}</p>{items.map(x=><div className="catalog-row" key={x.id}><span>{x.name} — نسخه {x.version} — سال {x.contractYear||"—"}{x.effectiveFrom?` — از ${formatJalaliDate(x.effectiveFrom)}`:""}{x.effectiveTo?` تا ${formatJalaliDate(x.effectiveTo)}`:""}</span><b>{x.isActive?"فعال":"غیرفعال"}</b><button onClick={()=>void updateContractTemplate(x.id,{name:x.name,contractType:x.contractType,description:x.description,contractGroupId:x.contractGroupId,contractYear:x.contractYear,effectiveFrom:x.effectiveFrom,effectiveTo:x.effectiveTo,isActive:!x.isActive}).then(load)}>{x.isActive?"غیرفعال‌سازی":"فعال‌سازی"}</button><button onClick={()=>window.confirm("حذف نرم شود؟")&&void deleteContractTemplate(x.id).then(load)}>حذف</button></div>)}</article></section></main>;
}
