"use client";
import { FormEvent, useEffect, useState } from "react";
import { deleteContractCatalog, listContractCatalog, OrganizationParty, saveContractCatalog } from "../../../lib/api";
const size=20;
export default function ContractPartiesPage(){
 const [items,setItems]=useState<OrganizationParty[]>([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[name,setName]=useState(""),[nationalIdentifier,setNationalIdentifier]=useState(""),[representativeName,setRepresentativeName]=useState(""),[contactInfo,setContactInfo]=useState(""),[active,setActive]=useState(true),[edit,setEdit]=useState<OrganizationParty|null>(null),[message,setMessage]=useState("");
 async function load(p=page){try{const r=await listContractCatalog<OrganizationParty>("parties",p,size);setItems(r.items);setPage(r.pageNumber);setPages(Math.max(1,r.totalPages));}catch{setMessage("دریافت طرف‌های قرارداد انجام نشد.")}}useEffect(()=>{void load(1)},[]);
 function reset(){setEdit(null);setName("");setNationalIdentifier("");setRepresentativeName("");setContactInfo("");setActive(true)}
 async function submit(e:FormEvent){e.preventDefault();if(!name.trim())return;try{await saveContractCatalog("parties",{name,nationalIdentifier:nationalIdentifier||null,representativeName:representativeName||null,contactInfo:contactInfo||null,isActive:active},edit?.id);reset();await load(edit?page:1);setMessage("ذخیره شد.")}catch{setMessage("ذخیره طرف قرارداد انجام نشد.")}}
 return <main className="app-shell" dir="rtl"><section className="page-content"><header className="page-header"><p className="eyebrow">اطلاعات پایه</p><h1>طرف‌های قرارداد</h1><p>شرکت‌ها و اشخاص قابل انتخاب در قرارداد را ثبت و مدیریت کنید.</p></header><article className="panel"><form className="form-grid" onSubmit={e=>void submit(e)}><input placeholder="نام شخص یا شرکت" value={name} onChange={e=>setName(e.target.value)} required/><input placeholder="شناسه ملی" value={nationalIdentifier} onChange={e=>setNationalIdentifier(e.target.value)}/><input placeholder="نام نماینده" value={representativeName} onChange={e=>setRepresentativeName(e.target.value)}/><input placeholder="اطلاعات تماس" value={contactInfo} onChange={e=>setContactInfo(e.target.value)}/><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> فعال</label><button className="primary-button">{edit?"ذخیره":"ثبت طرف قرارداد"}</button>{edit&&<button type="button" onClick={reset}>انصراف</button>}</form></article><article className="panel"><h2>فهرست طرف‌های قرارداد</h2><p>{message}</p>{items.map(x=><div className="catalog-row" key={x.id}><span>{x.name}{x.nationalIdentifier?` — ${x.nationalIdentifier}`:""}</span><b>{x.isActive?"فعال":"غیرفعال"}</b><button onClick={()=>void saveContractCatalog("parties",{name:x.name,nationalIdentifier:x.nationalIdentifier||null,representativeName:x.representativeName||null,contactInfo:x.contactInfo||null,isActive:!x.isActive},x.id).then(()=>load())}>{x.isActive?"غیرفعال‌سازی":"فعال‌سازی"}</button><button onClick={()=>{setEdit(x);setName(x.name);setNationalIdentifier(x.nationalIdentifier||"");setRepresentativeName(x.representativeName||"");setContactInfo(x.contactInfo||"");setActive(x.isActive)}}>ویرایش</button><button onClick={()=>window.confirm("حذف نرم شود؟")&&void deleteContractCatalog("parties",x.id).then(()=>load())}>حذف</button></div>)}<nav className="pagination"><button disabled={page===1} onClick={()=>void load(page-1)}>قبلی</button><span>{page} از {pages}</span><button disabled={page===pages} onClick={()=>void load(page+1)}>بعدی</button></nav></article></section></main>
}
