// const defaultColors = require('tailwindcss/colors');
const { createGlobPatternsForDependencies } = require('@nrwl/react/tailwind');
const { join } = require('path');

module.exports = {
  content: [
    join(__dirname, 'apps/**/!(*.stories|*.spec).{ts,tsx,html}'),
    join(__dirname, 'libs/**/!(*.stories|*.spec).{ts,tsx,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  darkMode: 'class',
  safelist: [
    'bg-listingNotChecked',
    'bg-listingNoContent',
    'text-listingIrrelevantButton',
    'text-listingModalRejectButton',
  ],
  theme: {
    screens: {
      xs: { min: '0', max: '389px' },
      sm: { min: '390px', max: '639px' },
      md: { min: '640px', max: '767px' },
      lg: { min: '768px', max: '1023px' },
      xl: { min: '1024px', max: '1279px' },
      '2xl': { min: '1280px' },
    },
    fontFamily: {
      'iransans-regular': ['iransans-regular'],
      'iransans-light': ['iransans-light'],
    },
    fontSize: {
      extratiny: '0.75rem',
      tiny: '.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '2rem',
      '4xl': '2.5rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
    },
    fontWeight: {
      thin: 100,
      'extra-light': 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      'extra-bold': 800,
      black: 900,
    },
    textAlign: { start: 'start', end: 'end' },
    extend: {
      boxShadow: {
        simple: '0 0 4px 0 rgba(0, 0, 0, 0.2)',
      },
      direction: {
        rtl: 'rtl',
      },
      colors: {
        white: '#fff',
        black: '#000',
        red: '#FF0000',
        link: '#0038C7',
        liver: '#B30B00',
        purple: '#D39E46',
        gold: '#CB8100',
        lightGold: 'rgba(210, 171, 103, 0.5)',
        darkGreen: '#014258',
        green: 'green',
        pink: 'pink',
        lightGray: '#F7F7F7',
        grayBorder: '#c4c4c4',
        lightPurple: 'rgba(158, 0, 255, 0.4)',
        veryLightPurple: 'rgba(158, 0, 255, 0.1)',
        lightGrayOpacity: 'rgba(196, 196, 196, 0.2)',
        blue: '#2029FF',
        blackOpacity: 'rgba(0, 0, 0, 0.2)',
        lightBlue: 'rgba(182, 185, 255, 0.3)',
        gray: 'rgba(196, 196, 196)',
        teal: '#00BA77',
        tealLight: 'rgba(0, 186, 119, 0.3)',
        headerGray: '#5B5B5B',
        taxLightBlue: '#EEF5FF',
        yellow: '#FFD12F',
        buttonBlue: '#0066FF',
        grayBackground: '#F4F4F4',
        regionHallTableGray: '#f3f3f5',
        regionHallBorderTableGray: '#949599',
        row: '#E5E5E5',
        bg: '#F4F4F4',
        darkGray: '#7E7E7E',
        listingPrimaryColor: '#17a2b8',
        listingSecondaryColor: '#B18F47',
        listingTertiaryColor: '#10375c',
        listingBaseColorModal: '#10375c',
        listingModalAcceptButton: '#04aa6d',
        listingModalRejectButton: '#f57f17',
        listingIrrelevantButton: '#e53935',
        listingModalRegisterButton: '#10375c',
        listingModalCancelButton: '#d63333',
        dossierModalTableConfirmButton: '#04aa6d',
        dossierModalTableRejectButton: '#d50000',
        listingBackgroundColor: '#dedede',
        brown: '#87370f',
        listingNotChecked: '#17a2b8',
        listingNoContent: '#b0b0b0',
        corporateSurveyPrimaryColor: '#',
        corporateSurveySecondaryColor: '#',
        corporateSurveyTertiaryColor: '#',
      },
    },
  },
  plugins: [],
};
