// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Infrastructure.Persistence;

#nullable disable

namespace Notification.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notification.Application.Domain.Entities.NotificationInfo", b =>
                {
                    b.Property<Guid>("NotificationInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<byte>("AccessSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtraInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Notif_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationInfoId");

                    b.ToTable("NotificationInfo", (string)null);
                });

            modelBuilder.Entity("Notification.Application.Domain.Entities.NotificationUser", b =>
                {
                    b.Property<Guid>("NotificationUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid>("NotificationInfoId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<DateTime?>("ReadDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationUserId");

                    b.HasIndex("NotificationInfoId");

                    b.ToTable("NotificationUser", (string)null);
                });

            modelBuilder.Entity("Notification.Application.Domain.Entities.NotificationInfo", b =>
                {
                    b.OwnsOne("Notification.Application.Domain.Entities.InstrumentInfo", "Instrument", b1 =>
                        {
                            b1.Property<Guid>("NotificationInfoId")
                                .HasColumnType("UniqueIdentifier");

                            b1.Property<string>("CompanyName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long?>("Investment")
                                .HasColumnType("bigint");

                            b1.Property<byte?>("MarketTypeId")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SymbolCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SymbolName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NotificationInfoId");

                            b1.ToTable("NotificationInfo");

                            b1.WithOwner()
                                .HasForeignKey("NotificationInfoId");
                        });

                    b.Navigation("Instrument")
                        .IsRequired();
                });

            modelBuilder.Entity("Notification.Application.Domain.Entities.NotificationUser", b =>
                {
                    b.HasOne("Notification.Application.Domain.Entities.NotificationInfo", "NotificationInfo")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("NotificationInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationInfo");
                });

            modelBuilder.Entity("Notification.Application.Domain.Entities.NotificationInfo", b =>
                {
                    b.Navigation("NotificationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
