"use client";
import { useEffect, useState } from "react";
import { ComplianceCriterion, DocumentGroup, DocumentGroupCriterion, getDocumentGroupCriteria, listCriteria, listDocumentGroups, saveDocumentGroupCriteria } from "../../../lib/api";
export default function DocumentGroupCriteriaPage(){
 const [groups,setGroups]=useState<DocumentGroup[]>([]),[criteria,setCriteria]=useState<ComplianceCriterion[]>([]),[groupId,setGroupId]=useState(""),[items,setItems]=useState<DocumentGroupCriterion[]>([]),[message,setMessage]=useState("");
 useEffect(()=>{void Promise.all([listDocumentGroups(),listCriteria(1,100)]).then(([g,c])=>{setGroups(g);setCriteria(c.items)}).catch(()=>setMessage("دریافت اطلاعات انجام نشد."))},[]);
 useEffect(()=>{if(!groupId){setItems([]);return}void getDocumentGroupCriteria(groupId).then(setItems).catch(()=>setMessage("دریافت معیارها انجام نشد."))},[groupId]);
 function toggle(c:ComplianceCriterion,checked:boolean){setItems(x=>checked?[...x,{id:"",complianceCriterionId:c.id,code:c.code,title:c.title,weight:c.defaultWeight,isCritical:c.isCriticalByDefault,order:x.length+1}]:x.filter(i=>i.complianceCriterionId!==c.id))}
 async function save(){if(!groupId)return;try{await saveDocumentGroupCriteria(groupId,items.map(x=>({complianceCriterionId:x.complianceCriterionId,weight:x.weight,isCritical:x.isCritical,order:x.order})));setMessage("ذخیره شد.")}catch{setMessage("ذخیره انجام نشد.")}}
 return <main className="app-shell" dir="rtl"><section className="page-content"><header className="page-header"><p className="eyebrow">اطلاعات پایه</p><h1>معیارهای گروه سند</h1></header><article className="panel"><select value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">گروه سند</option>{groups.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{groupId&&criteria.map(c=>{const item=items.find(x=>x.complianceCriterionId===c.id);return <div className="catalog-row" key={c.id}><label><input type="checkbox" checked={!!item} onChange={e=>toggle(c,e.target.checked)}/>{c.code} — {c.title}</label>{item&&<><input type="number" value={item.weight} onChange={e=>setItems(rows=>rows.map(x=>x.complianceCriterionId===c.id?{...x,weight:Number(e.target.value)}:x))}/><label><input type="checkbox" checked={item.isCritical} onChange={e=>setItems(rows=>rows.map(x=>x.complianceCriterionId===c.id?{...x,isCritical:e.target.checked}:x))}/> حیاتی</label></>}</div>})}<button className="primary-button" disabled={!groupId} onClick={()=>void save()}>ذخیره</button><p>{message}</p></article></section></main>;
}
