"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ContractStatusDefinition, deleteContractCatalog, listContractCatalog, saveContractCatalog } from "../../../lib/api";
const size=20;
export default function ContractStatusesPage(){
 const [items,setItems]=useState<ContractStatusDefinition[]>([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[name,setName]=useState(""),[order,setOrder]=useState(1),[color,setColor]=useState("#6658df"),[active,setActive]=useState(true),[edit,setEdit]=useState<ContractStatusDefinition|null>(null),[error,setError]=useState("");
 const load=useCallback(async(p=page)=>{try{const r=await listContractCatalog<ContractStatusDefinition>("statuses",p,size);setItems(r.items);setPage(r.pageNumber);setPages(Math.max(1,r.totalPages));}catch{setError("دریافت وضعیت‌ها انجام نشد.")}},[page]);useEffect(()=>{void load(1)},[]);
 const reset=()=>{setEdit(null);setName("");setOrder(items.length+1);setColor("#6658df");setActive(true)};
 async function submit(e:FormEvent){e.preventDefault();if(!name.trim())return;await saveContractCatalog("statuses",{name,order,color,isActive:active},edit?.id);reset();await load(edit?page:1)}
 return <main className="app-shell" dir="rtl"><section className="page-content"><header className="page-header"><p className="eyebrow">اطلاعات پایه</p><h1>وضعیت‌های قرارداد</h1><p>وضعیت‌ها توسط هر سازمان تعریف و در ثبت قرارداد انتخاب می‌شوند.</p></header><article className="panel"><form className="form-grid" onSubmit={e=>void submit(e)}><input placeholder="نام وضعیت" value={name} onChange={e=>setName(e.target.value)} required/><input type="number" value={order} onChange={e=>setOrder(Number(e.target.value))}/><input type="color" value={color} onChange={e=>setColor(e.target.value)}/><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> فعال</label><button className="primary-button">{edit?"ذخیره":"ثبت وضعیت"}</button>{edit&&<button type="button" onClick={reset}>انصراف</button>}</form></article><article className="panel"><h2>فهرست وضعیت‌ها</h2>{error&&<p className="error-text">{error}</p>}{items.map(x=><div className="catalog-row" key={x.id}><span><i style={{display:"inline-block",width:12,height:12,borderRadius:99,background:x.color}}/> {x.order}. {x.name}</span><b>{x.isActive?"فعال":"غیرفعال"}</b><button onClick={()=>void saveContractCatalog("statuses",{name:x.name,order:x.order,color:x.color,isActive:!x.isActive},x.id).then(()=>load())}>{x.isActive?"غیرفعال‌سازی":"فعال‌سازی"}</button><button onClick={()=>{setEdit(x);setName(x.name);setOrder(x.order);setColor(x.color);setActive(x.isActive)}}>ویرایش</button><button onClick={()=>window.confirm("حذف نرم شود؟")&&void deleteContractCatalog("statuses",x.id).then(()=>load())}>حذف</button></div>)}<nav className="pagination"><button disabled={page===1} onClick={()=>void load(page-1)}>قبلی</button><span>{page} از {pages}</span><button disabled={page===pages} onClick={()=>void load(page+1)}>بعدی</button></nav></article></section></main>
}
