// <auto-generated />
using System;
using IdentityServer.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityServer.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721163100_AddImpersonationAudit")]
    partial class AddImpersonationAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessForm", b =>
                {
                    b.Property<int>("AccessFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessFormId"));

                    b.Property<int>("AccessSystemId")
                        .HasColumnType("Int");

                    b.Property<string>("FormTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AccessFormId");

                    b.HasIndex("AccessSystemId");

                    b.ToTable("AccessForm", (string)null);
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessMenu", b =>
                {
                    b.Property<int>("AccessMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessMenuId"));

                    b.Property<int?>("AccessFormId")
                        .HasColumnType("Int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentRef")
                        .HasColumnType("Int");

                    b.HasKey("AccessMenuId");

                    b.HasIndex("AccessFormId");

                    b.HasIndex("ParentRef");

                    b.ToTable("AccessMenu", (string)null);
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessRole", b =>
                {
                    b.Property<int>("AccessRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessRoleId"));

                    b.Property<int>("AccessMenuId")
                        .HasColumnType("Int");

                    b.Property<bool?>("HasPersianAccess")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccessRoleId");

                    b.HasIndex("AccessMenuId");

                    b.ToTable("AccessRole", (string)null);
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessSystem", b =>
                {
                    b.Property<int>("AccessSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessSystemId"));

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SystemTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AccessSystemId");

                    b.ToTable("AccessSystem", (string)null);
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessSystemRole", b =>
                {
                    b.Property<int>("AccessSystemRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessSystemRoleId"));

                    b.Property<int>("AccessSystemId")
                        .HasColumnType("Int");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccessSystemRoleId");

                    b.HasIndex("AccessSystemId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccessSystemRole", (string)null);
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessUserGrant", b =>
                {
                    b.Property<int>("AccessUserGrantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessUserGrantId"));

                    b.Property<int>("AccessMenuId")
                        .HasColumnType("Int");

                    b.Property<int>("AccessSystemId")
                        .HasColumnType("Int");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccessUserGrantId");

                    b.HasIndex("AccessMenuId");

                    b.HasIndex("AccessSystemId");

                    b.HasIndex("UserId", "AccessSystemId", "AccessMenuId")
                        .IsUnique();

                    b.ToTable("AccessUserGrant", (string)null);
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ActionInfo", b =>
                {
                    b.Property<int>("ActionInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionInfoId"));

                    b.Property<string>("ActionInfoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("Int");

                    b.Property<int>("SectionInfoId")
                        .HasColumnType("Int");

                    b.HasKey("ActionInfoId");

                    b.HasIndex("SectionInfoId");

                    b.ToTable("ActionInfos");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccessSystemId")
                        .HasColumnType("Int");

                    b.Property<Guid?>("ApplicationRoleGroupId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AccessSystemId");

                    b.HasIndex("ApplicationRoleGroupId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ApplicationRoleGroup", b =>
                {
                    b.Property<Guid>("ApplicationRoleGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<string>("ApplicationRoleGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("Int");

                    b.HasKey("ApplicationRoleGroupId");

                    b.ToTable("ApplicationRoleGroups");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CodeSendedDateTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DepartmentId")
                        .HasColumnType("TinyInt");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Bit")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ApplicationUserAccess", b =>
                {
                    b.Property<Guid>("ApplicationUserAccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier");

                    b.Property<byte>("AccessMode")
                        .HasColumnType("TinyInt");

                    b.Property<int>("ActionInfoId")
                        .HasColumnType("Int");

                    b.Property<Guid?>("ApplicationRoleGroupId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid?>("ApplicationRoleId")
                        .HasColumnType("UniqueIdentifier");

                    b.HasKey("ApplicationUserAccessId");

                    b.HasIndex("ActionInfoId");

                    b.HasIndex("ApplicationRoleGroupId");

                    b.HasIndex("ApplicationRoleId");

                    b.ToTable("ApplicationUserAccesses");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ImpersonationAudit", b =>
                {
                    b.Property<long>("ImpersonationAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImpersonationAuditId"));

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImpersonationAuditId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("SessionId", "Event")
                        .IsUnique();

                    b.ToTable("ImpersonationAudits", (string)null);
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.SectionInfo", b =>
                {
                    b.Property<int>("SectionInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionInfoId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("Int");

                    b.Property<string>("SectionInfoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubSystemId")
                        .HasColumnType("Int");

                    b.HasKey("SectionInfoId");

                    b.HasIndex("SubSystemId");

                    b.ToTable("SectionInfos");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.SubSystemInfo", b =>
                {
                    b.Property<int>("SubSystemInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubSystemInfoId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("Int");

                    b.Property<string>("SubSystemInfoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubSystemInfoId");

                    b.ToTable("SubSystemInfos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessForm", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.AccessSystem", "AccessSystem")
                        .WithMany("AccessForms")
                        .HasForeignKey("AccessSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccessSystem");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessMenu", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.AccessForm", "AccessForm")
                        .WithMany("AccessMenus")
                        .HasForeignKey("AccessFormId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdentityServer.Domain.Entities.AccessMenu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentRef")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccessForm");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessRole", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.AccessMenu", "AccessMenu")
                        .WithMany("AccessRoles")
                        .HasForeignKey("AccessMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccessMenu");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessSystemRole", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.AccessSystem", "AccessSystem")
                        .WithMany("AccessSystemRoles")
                        .HasForeignKey("AccessSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityServer.Domain.Entities.ApplicationRole", "ApplicationRole")
                        .WithMany("AccessSystemRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccessSystem");

                    b.Navigation("ApplicationRole");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessUserGrant", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.AccessMenu", "AccessMenu")
                        .WithMany()
                        .HasForeignKey("AccessMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityServer.Domain.Entities.AccessSystem", "AccessSystem")
                        .WithMany()
                        .HasForeignKey("AccessSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityServer.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccessMenu");

                    b.Navigation("AccessSystem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ActionInfo", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.SectionInfo", "SectionInfo")
                        .WithMany("ActionInfos")
                        .HasForeignKey("SectionInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SectionInfo");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ApplicationRole", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.AccessSystem", null)
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("AccessSystemId");

                    b.HasOne("IdentityServer.Domain.Entities.ApplicationRoleGroup", "ApplicationRoleGroup")
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("ApplicationRoleGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationRoleGroup");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ApplicationUserAccess", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.ActionInfo", "ActionInfo")
                        .WithMany("ApplicationUserAccesses")
                        .HasForeignKey("ActionInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityServer.Domain.Entities.ApplicationRoleGroup", "ApplicationRoleGroup")
                        .WithMany("ApplicationUserAccesses")
                        .HasForeignKey("ApplicationRoleGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdentityServer.Domain.Entities.ApplicationRole", "ApplicationRole")
                        .WithMany("ApplicationUserAccesses")
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActionInfo");

                    b.Navigation("ApplicationRole");

                    b.Navigation("ApplicationRoleGroup");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.SectionInfo", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.SubSystemInfo", "SubSystem")
                        .WithMany("SectionInfos")
                        .HasForeignKey("SubSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubSystem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityServer.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("IdentityServer.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessForm", b =>
                {
                    b.Navigation("AccessMenus");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessMenu", b =>
                {
                    b.Navigation("AccessRoles");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.AccessSystem", b =>
                {
                    b.Navigation("AccessForms");

                    b.Navigation("AccessSystemRoles");

                    b.Navigation("ApplicationRoles");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ActionInfo", b =>
                {
                    b.Navigation("ApplicationUserAccesses");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ApplicationRole", b =>
                {
                    b.Navigation("AccessSystemRoles");

                    b.Navigation("ApplicationUserAccesses");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.ApplicationRoleGroup", b =>
                {
                    b.Navigation("ApplicationRoles");

                    b.Navigation("ApplicationUserAccesses");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.SectionInfo", b =>
                {
                    b.Navigation("ActionInfos");
                });

            modelBuilder.Entity("IdentityServer.Domain.Entities.SubSystemInfo", b =>
                {
                    b.Navigation("SectionInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
